### ISSUE TITLE
Multi GPU training

### ISSUE THREAD

**Issue by WHQCHINA** [clovaai/deep-text-recognition-benchmark#1]
Hi，
    how to train use mutil gpus in this project? try to set CUDA_VISIBLE_DEVICES=0,1, but it is wrong.
best

**Comment by ku21fan** [comment]
@WHQCHINA Thank you for the report !
We reproduced this issue and fixed it with [this solution](https://discuss.pytorch.org/t/index-select-with-dataparallel-arguments-are-located-on-different-gpus/10229/7).
Please check the recent [commit](https://github.com/clovaai/deep-text-recognition-benchmark/commit/7553b47a7c3373d24de228169383b0dc762845fc).

Thank you.

**Comment by WHQCHINA** [comment]
@ku21fan thanks，it is work!

**Comment by WHQCHINA** [comment]
@ku21fan mutil GPU training and workers number > 0 ,  it is GPUs stuck for long time.

**Comment by ku21fan** [comment]
@WHQCHINA In our environment (Intel Xeon(R) E5-2630 v4 2.20GHz CPU and NVIDIA TESLA P40 GPU), 
we could not reproduce 'GPUs stuck' with worker number 4 x num_gpu.

Though we could not reproduce it, it could happen with a different environment, so we added a comment to [here](https://github.com/clovaai/deep-text-recognition-benchmark/blob/master/train.py#L268).
Thank you for report and solution!

**Comment by WHQCHINA** [comment]
Hi，
    I want to known how long you to train a TPS+Resnet+BiLSTM+Attention model? I train 1000 iterations using one hour using two NVIDIA TESLA P40 GPUs. 
    I have train a model using  synthetic data, but test in real data is bad, can you give me some davise? I train model using real data now.

**Comment by ku21fan** [comment]
@WHQCHINA 
1. how long you train a TPS+Resnet+BiLSTM+Attention model? with P40 GPU
The training time takes about 2days with 1 GPU and takes about 31 hours with 2 GPUs. 
We are re-training the model to re-check training time for now.
I attached the training log of them.
[log_train_1gpu.txt](https://github.com/clovaai/deep-text-recognition-benchmark/files/3077342/log_train_1gpu.txt)
[log_train_2gpu.txt](https://github.com/clovaai/deep-text-recognition-benchmark/files/3077340/log_train_2gpu.txt)
It took 1500 seconds per 2000 iteration with 2 GPUs. 
I am wondering if you have used cudnn.
In our experiment, `cudnn.benchmark = True` accelerate the training time greatly.

2. Combining synthetic data and real data and using it as a training data set would be a good plan. 
try it with `--select_data` and `--batch_ratio` options.

best
