### ISSUE TITLE
I cannot download the pretrained model in google drive. Is there a resource in baidu Netdisk?

### ISSUE THREAD

**Issue by tinggh** [clovaai/deep-text-recognition-benchmark#10]

**Comment by ku21fan** [comment]
Currently, we don't have a resource in baidu netdisk.
I will try to upload the resource in baidu netdisk.

**Comment by ku21fan** [comment]
I successfully uploaded models in Baidu Netdisk.
url: https://pan.baidu.com/s/1KSNLv4EY3zFWHpBYlpFCBQ 
password: rryk 

Best.

**Comment by softwaregitgub** [comment]
> I successfully uploaded models in Baidu Netdisk.
> url: https://pan.baidu.com/s/1KSNLv4EY3zFWHpBYlpFCBQ
> password: rryk
> 
> Best.

Is the data_lmdb_baidu.zip file doesn't work.
当我试图解压文件的时候显示 z01出现错误

When I tried to unzip the data_lmdb_baidu.zip, it showed that z01 had an error.

**Comment by ku21fan** [comment]
@softwaregitgub 
hello, 

Did you tried to unzip after download 5files below?
data_lmdb_baidu.zip
data_lmdb_baidu.z01
data_lmdb_baidu.z02
data_lmdb_baidu.z03
data_lmdb_baidu.z04

You should download all of them and then unzip data_lmdb_baidu.zip
Hope it helps :)

Best

**Comment by softwaregitgub** [comment]
> @softwaregitgub
> hello,
> 
> Did you try to unzip after download 5files below?
> data_lmdb_baidu.zip
> data_lmdb_baidu.z01
> data_lmdb_baidu.z02
> data_lmdb_baidu.z03
> data_lmdb_baidu.z04
> 
> You should download all of them and then unzip data_lmdb_baidu.zip
> Hope it helps :)
> 
> Best

yes,i had download all of them together.! E:\BaiduNetdiskDownload\deep_text_recognition\data_lmdb_baidu.z01: 文件 C:\Users\AppData\Local\Temp\Rar$DIa23972.17102\data_lmdb_release.zip 里出现校验和错误。该文件已损坏。
! E:\BaiduNetdiskDownload\deep_text_recognition\data_lmdb_baidu.z01: 压缩文件已损坏
wrong show like this.

**Comment by ku21fan** [comment]
@softwaregitgub 
umm.. I tried to check on my computer, and I succeed to unzip it with 5 files.

It seems like something went wrong :(
Could you check the size of data_lmdb_baidu.z01 file is 3.81 GB?
or Could you re-download z01?

**Comment by softwaregitgub** [comment]
the z01 is 3.80 GB (4,089,446,400 字节)，data_lmdb_baidu.zip is 3.55 GB (3,814,454,325 字节) and i had re-download all the file, but had the same wrong。

**Comment by softwaregitgub** [comment]
> @softwaregitgub
> umm.. I tried to check on my computer, and I succeed to unzip it with 5 files.
> 
> It seems like something went wrong :(
> Could you check the size of data_lmdb_baidu.z01 file is 3.81 GB?
> or Could you re-download z01?

the z01 is 3.80 GB (4,089,446,400 字节)，data_lmdb_baidu.zip is 3.55 GB (3,814,454,325 字节) and i had re-download all the file, but had the same wrong。

**Comment by softwaregitgub** [comment]
> @softwaregitgub
> Can you try to unzip with software such as alzip or bandizip? instead of `unzip` command.
> Actually, I made this zip files with bandizip software, so it might cause this error.

![1563502202(1)](https://user-images.githubusercontent.com/40431492/61504298-7bcf7100-aa0d-11e9-9b92-3ed7fc5cfb3b.jpg)
I used the bandizip , the error still happened.

**Comment by ku21fan** [comment]
@softwaregitgub 
Now I am re-uploading the data_lmdb files in [data_lmdb_reupload folder](https://pan.baidu.com/s/1KSNLv4EY3zFWHpBYlpFCBQ#list/path=%2Fdeep_text_recognition%2Fdata_lmdb_reupload)
It will take about 3 hours to be uploaded.
After that, please download this file and try to unzip it again.
Hope it works...!

**Comment by softwaregitgub** [comment]
> @softwaregitgub
> Now I am re-uploading the data_lmdb files in [data_lmdb_reupload folder](https://pan.baidu.com/s/1KSNLv4EY3zFWHpBYlpFCBQ#list/path=%2Fdeep_text_recognition%2Fdata_lmdb_reupload)
> It will take about 3 hours to be uploaded.
> After that, please download this file and try to unzip it again.
> Hope it works...!

Many thanks for your help! it works now.

**Comment by CuriousCat-7** [comment]
what??? So I should use Bandizip in Windows, right?

**Comment by ku21fan** [comment]
@CuriousCat-7 I have not tried unzip data_lmdb_baidu in Linux or Mac OS. 
Try it your own environment and if you have some trouble, please notify us.
