### ISSUE TITLE
regarding normalised edit distance metric computed in test.py.

### ISSUE THREAD

**Issue by rahzaazhar** [clovaai/deep-text-recognition-benchmark#100]
Is the computed metric the same as the one used for evaluation on the ICDARMLT19 challenge
shouldn't the below lines be added to the test.py to compute normalised edit distance 
`norm_ED = norm_ED/float(length_of_data)`
`norm_ED = 1-norm_ED`

**Comment by rahzaazhar** [comment]
@ku21fan

**Comment by ku21fan** [comment]
Hello,

Good point!
In our `test.py`, we used general normalized edit distance which just divides ED with `len(gt)`.

To change it into ICDAR2019 metric, we used the below snippet.
```
    if len(gt) > len(pred):
        norm_ED += 1 - edit_distance(pred, gt) / len(gt)
    else:
        norm_ED += 1 - edit_distance(pred, gt) / len(pred)
```
or 
```
        norm_ED += 1 - edit_distance(pred, gt) / max( len(gt), len(pred))
```

Best.
