### ISSUE TITLE
Train your own bank card data erro:AssertionError: datasets should not be an empty iterable

### ISSUE THREAD

**Issue by cuimiao187561** [clovaai/deep-text-recognition-benchmark#101]
[shakey@xiaoi-778 deep-text-recognition-benchmark]$  CUDA_VISIBLE_DEVICES=0 python3 train.py --train_data ./data_lmdb_release/training/ --valid_data ./data_lmdb_release/validation/ --select_data MJ-ST --batch_ratio 0.5-0.5 --Transformation TPS --FeatureExtraction ResNet --SequenceModeling BiLSTM --Prediction Attn
--------------------------------------------------------------------------------
dataset_root: ./data_lmdb_release/training/
opt.select_data: ['MJ', 'ST']
opt.batch_ratio: ['0.5', '0.5']
--------------------------------------------------------------------------------
dataset_root:    ./data_lmdb_release/training/   dataset: MJ
Traceback (most recent call last):
  File "train.py", line 302, in <module>
    train(opt)
  File "train.py", line 26, in train
    train_dataset = Batch_Balanced_Dataset(opt)
  File "/opt/shakey/deep-learning/deep-text-recognition-benchmark/dataset.py", line 37, in __init__
    _dataset = hierarchical_dataset(root=opt.train_data, opt=opt, select_data=[selected_d])
  File "/opt/shakey/deep-learning/deep-text-recognition-benchmark/dataset.py", line 106, in hierarchical_dataset
    concatenated_dataset = ConcatDataset(dataset_list)
  File "/usr/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataset.py", line 187, in __init__
    assert len(datasets) > 0, 'datasets should not be an empty iterable'
AssertionError: datasets should not be an empty iterable

**Comment by ku21fan** [comment]
Hello, 

Check `--select_data`, `--train_data`, `--valid_data`.
[This](https://github.com/clovaai/deep-text-recognition-benchmark#when-you-need-to-train-on-your-own-dataset-or-non-latin-language-datasets) will help you.

Best

**Comment by IsaacBerman** [comment]
The output of create_lmdb_dataset.py are 2 .mdb files, which files should we set as paths for --train_data and --select_data? I am getting the same error when setting --train_data to the directory of the data.mdb file.

**Comment by ku21fan** [comment]
@IsaacBerman Hello, 

should set the folder path for `--train_data` and folder name for `--select_data`.

```
assert len(datasets) > 0, 'datasets should not be an empty iterable'
AssertionError: datasets should not be an empty iterable
```
The above error would occur when the length of the dataset is 0,
which means the lmdb dataset does not contain data.
Recommend to check your .mdb files again.

Best,

**Comment by freedom9393** [comment]
When you are running the scipt for training, just check if your path to `.lmdb` files is correct
