### ISSUE TITLE
class GridGenerator

### ISSUE THREAD

**Issue by chen849157649** [clovaai/deep-text-recognition-benchmark#102]
hello, you define class GridGenerator， why not define forward method？i do not know mean, tell me ? thank you

**Comment by ku21fan** [comment]
Hello, 

As you said, GridGenerator has `def build_P_prime()` and it could be `def forward()`.
We used `def build_P_prime()` instead of `def forward()` for readability.

Best

**Comment by chen849157649** [comment]
> Hello,
> 
> As you said, GridGenerator has `def build_P_prime()` and it could be `def forward()`.
> We used `def build_P_prime()` instead of `def forward()` for readability.
> 
> Best

@ku21fan , thank you!, because GridGenerator not backward, only forward, so you  used `def build_P_prime()` instead of `def forward()` for readability????
