### ISSUE TITLE
Does this work on rotated texts?

### ISSUE THREAD

**Issue by xxxpsyduck** [clovaai/deep-text-recognition-benchmark#106]
I tried to trained this on both normal texts and their 180-degree-rotated version. The val accuracy is quite high but the real test result is not acceptable. So I wonder what is the biggest angle of text rotation that this solution can work well

**Comment by michaeltremeer** [comment]
To solve this problem for images with unknown input rotation, I ran inference for all fields in upright orientation, saved the confidence scores, then rotated the images 180 degrees and ran inference again, saving confidence sores again. Then you can compare the median confidence scores for each run and keep the predictions from the run with the highest median score.
