### ISSUE TITLE
assertion error

### ISSUE THREAD

**Issue by yyyash8** [clovaai/deep-text-recognition-benchmark#109]
:~/deep-text-recognition-benchmark$ CUDA_VISIBLE_DEVICES=0 python3 train.py --train_data /home/lincode/deep-text-recognition-benchmark/result/ --valid_data validate/ --select_data /home/lincode/deep-text-recognition-benchmark/TextRecognitionDataGenerator/TextRecognitionDataGenerator/out --batch_ratio .8  --Transformation TPS --FeatureExtraction ResNet --SequenceModeling BiLSTM --Prediction Attn
Filtering the images containing characters which are not in opt.character
Filtering the images whose label is longer than opt.batch_max_length
--------------------------------------------------------------------------------
dataset_root: /home/lincode/deep-text-recognition-benchmark/result/
opt.select_data: ['/home/lincode/deep', 'text', 'recognition', 'benchmark/TextRecognitionDataGenerator/TextRecognitionDataGenerator/out']
opt.batch_ratio: ['.8']
Traceback (most recent call last):
  File "train.py", line 307, in <module>
    train(opt)
  File "train.py", line 31, in train
    train_dataset = Batch_Balanced_Dataset(opt)
  File "/home/lincode/deep-text-recognition-benchmark/dataset.py", line 27, in __init__
    assert len(opt.select_data) == len(opt.batch_ratio)
AssertionError

what to do?

**Comment by vinodckumar** [comment]
I am getting same error..what to do?

**Comment by yyyash8** [comment]
> I am getting same error..what to do?

#85  check this
