### ISSUE TITLE
Inference code

### ISSUE THREAD

**Issue by estimoelmo** [clovaai/deep-text-recognition-benchmark#11]
Hi, bravo for the great findings!

Do you have any inference script?

Thanks.

**Comment by ku21fan** [comment]
Hi, we have `test.py` for inference, 
and currently, I am going to make `demo.py` for the simplified version of `test.py`.
I will upload `demo.py` in this weak.
Thanks.

**Comment by sharavsambuu** [comment]
Hello, great repo!
Here is my naive attempt.
https://colab.research.google.com/drive/1PHnc_QYyf9b1_KJ1r15wYXaOXkdm1Mrk

**Comment by hasiftwistcode** [comment]
Thanks @sharavsambuu ! I changed it to best_accuracy.pth and it didn't work, is there any reason why?
And the model is pretty inaccurate with any type of images right? like this : https://drive.google.com/drive/folders/15SMmcdY9fzeKg6aHZjqlsfbqWNn2i6_0?usp=sharing

**Comment by sharavsambuu** [comment]
Hi @hasiftwistcode  if you want you use a best_accuracy.pth, please take an attention on the parser.character, it is using 36 characters '0123456789abcdefghijklmnopqrstuvwxyz'. Other one(case-sensitive version) is using 96 characters, string.printable[:-6]. I didn't evaluate an accuracy on my dataset yet.

**Comment by hasiftwistcode** [comment]
The model can even predict my input image though, but it is alright. Next time, ill use this model to train first on my dataset. Thanks for your help!

**Comment by sharavsambuu** [comment]
I updated notebook for your 4 images. Result seems not so good.

**Comment by hasiftwistcode** [comment]
Appreciate your effort! I've looked at it and yeah as expected. I am currently doing ocr for the identity card, I did crop the address to little pieces which the images are really small and surprisingly tesseract is pretty good at it (very image-sensitive). I tried kraken ocr but it wasn't good as tesseract.

**Comment by sharavsambuu** [comment]
Thank you for letting me know, I also working on similar project. Tried various repos and results were not so good, also tried google vision api and it is working perfect except their high api price. Also tried tesseract and it needs a lot of preprocessing in order to work well in my case. Currently scraping and collecting my own dataset in order to cope those problems :) I hope you will do well, cheers!

**Comment by ku21fan** [comment]
Sorry for the late update.
I just uploaded `demo.py`.
check the [run demo part](https://github.com/clovaai/deep-text-recognition-benchmark#run-demo-with-pretrained-model ) in the Readme.

Best regards.
