### ISSUE TITLE
How to resume training

### ISSUE THREAD

**Issue by yyyash8** [clovaai/deep-text-recognition-benchmark#110]
How to resume training when once stopped. I have the best_accuracy.pth file.

**Comment by inouetaka** [comment]
Do you have iter_100000.pth?
If you don't have it, you probably can't run it again.

If you want to adjust the output:
```python
# save model per 1e+5 iter.
if (i + 1) % 1e+5 == 0:
    torch.save(
           model.state_dict(), f'./saved_models/{opt.experiment_name}/iter_{i+1}.pth')
```

**Comment by yyyash8** [comment]
> Do you have iter_100000.pth?
> If you don't have it, you probably can't run it again.
> 
> If you want to adjust the output:
> train.py(212~215)
> 
> ```python
> # save model per 1e+5 iter.
> if (i + 1) % 1e+5 == 0:
>     torch.save(
>            model.state_dict(), f'./saved_models/{opt.experiment_name}/iter_{i+1}.pth')
> ```

I have the iter_ files also after every 2000 iterations. How to resume it.

**Comment by boy977** [comment]
@yyyash8 just add '--saved_model' option when running train.py

**Comment by inouetaka** [comment]
example
```
python3 train.py --train_data data_lmdb_release/train/MJ/****/  \
--valid_data data_lmdb_release/validation/****/ --select_data MJ \
--batch_ratio 1.0 --Transformation TPS --FeatureExtraction ResNet \
--SequenceModeling BiLSTM --Prediction CTC --saved_model saved_models/****/iter_2000.pth
```

**Comment by yyyash8** [comment]
Thanks
