### ISSUE TITLE
Transfer learning with pre-trained sensitive model; can't add new characters

### ISSUE THREAD

**Issue by omersert** [clovaai/deep-text-recognition-benchmark#114]
Hello, when I try to train TPS-ResNet-BiLSTM-Attn-case-sensitive.pth again with the goal of adding new characters like 'öüşç' I fail to change the --character parameter of TPS-ResNet-BiLSTM-Attn-case-sensitive.pth. I edited --character parameter in train.py and demo.py. This is the command I used in my terminal. 

python train.py --train_data \result\training --valid_data result\validation --Transformation TPS --FeatureExtraction ResNet --SequenceModeling BiLSTM --Prediction Attn --FT --sensitive --saved_model \TPS-ResNet-BiLSTM-Attn-case-sensitive_50000.pth --workers 0

and here is what I get as output 

![image](https://user-images.githubusercontent.com/53513065/69477864-6e335900-0dfc-11ea-9e6f-1336150e1d46.png)

as you can see the character parameters didn't change. Do you have a solution for this?

**Comment by nai-kon** [comment]
Hello @McLovinfromHawaii 
I also want to add new character to pre-trained model.
This issues was closed, but did you have any solution?

**Comment by Sayyam-Jain** [comment]
While loading model, did you try strict=False?

**Comment by McLovinfromHawaii** [comment]
@nai-kon Hello I solved this issue by changing `https://github.com/clovaai/deep-text-recognition-benchmark/blob/24749cd1a3e373a9e3180aa60b6d87ec4d621511/train.py#L287`  this line. Instead, I used a character string with 94 length.

**Comment by SaeedArisha** [comment]
Hi, I keep getting the sizemismatch error
