### ISSUE TITLE
 criterion = torch.nn.CTCLoss(zero_infinity=True).to(device) TypeError: __init__() got an unexpected keyword argument 'zero_infinity'

### ISSUE THREAD

**Issue by wyc2015fq** [clovaai/deep-text-recognition-benchmark#116]
torch ==1.1.0 ，why？

**Comment by ku21fan** [comment]
Hello, 

In PyTorch 1.1.0 document there is 'zero_infinity' in CTCLoss.
https://pytorch.org/docs/1.1.0/nn.html#torch.nn.CTCLoss

I guess it would be just a package issue.
I recommend to re-install PyTorch.

Best
