### ISSUE TITLE
too much softmax for CTC validation?

### ISSUE THREAD

**Issue by soldierofhell** [clovaai/deep-text-recognition-benchmark#117]
Hi @ku21fan,

In test.validation() you're doing log_softmax() in CTC scope:
https://github.com/clovaai/deep-text-recognition-benchmark/blob/master/test.py#L90
and then softmax() in common scope:
https://github.com/clovaai/deep-text-recognition-benchmark/blob/master/demo.py#L73

Seems like to much? :) It may affect confidence_score

Regards,

**Comment by ku21fan** [comment]
Hello, 

Yes, it was too much. 
Thank you for the report! 
I just delete & moved to log_softmax(2) in recent version. 8920de93e8f85e9ddcdf117d256b28ccf8ab4d09

However, it would not affect confidence_score.
Try without/with log_softmax(2) in CTC scope.
It would be same :)

Best
