### ISSUE TITLE
CTC beam decoder

### ISSUE THREAD

**Issue by soldierofhell** [clovaai/deep-text-recognition-benchmark#118]
Here we're using greedy decoding so the performance may be lower. Is there any PyTorch implementation of beam decoder like in tf:
https://www.tensorflow.org/api_docs/python/tf/nn/ctc_beam_search_decoder
or any other decoder (e.g. with dictionary)?

**Comment by ku21fan** [comment]
Hello, 

Maybe there is no official CTC beam decoder. (maybe you can find unofficial ones in Github).

And, Good point! we also had a question about it.
We tested with Tensorflow ctc beam search decoder with various beam_width.
However, there was no significant difference.

So, we just followed STR convention (use greedy decoding).
In STR field, people usually use greedy decoding in CTC. 
Below snippet is the part of [CRNN paper](https://arxiv.org/pdf/1507.05717.pdf).
![스크린샷_122719_074837_PM](https://user-images.githubusercontent.com/7953971/71514436-e00e2f00-28e1-11ea-99be-003e231781f7.jpg)

Best.
