### ISSUE TITLE
e = self.score(torch.tanh(batch_H_proj + prev_hidden_proj)) 

### ISSUE THREAD

**Issue by leigaoxiang** [clovaai/deep-text-recognition-benchmark#131]
how to compute alpha weights?,when i read your code,i found the way you use is slightly different can you tell which paper you references about torch.tanh(batch_H_proj + prev_hidden_proj) in e = self.score(torch.tanh(batch_H_proj + prev_hidden_proj)) 

thank you so much!

**Comment by ku21fan** [comment]
Hello, 

Just below that code
https://github.com/clovaai/deep-text-recognition-benchmark/blob/86451088248e0490ff8b5f74d33f7d014f6c249a/modules/prediction.py#L77

Check this paper https://arxiv.org/abs/1409.0473 
The detail of our code is also in the supplementary of our paper.

Best
