### ISSUE TITLE
img.sub_(0.5).div_(0.5)

### ISSUE THREAD

**Issue by leigaoxiang** [clovaai/deep-text-recognition-benchmark#133]
as my opinions the operation of img.sub_(0.5).div_(0.5) is useless， images is not normalised, is it?
thank you so much

**Comment by Sayyam-Jain** [comment]
@leigaoxiang _ refers to inplace operation.
It converts image to range [-1,1].

**Comment by leigaoxiang** [comment]
can you tell where the code is ,i can not find it ,thank you

**Comment by leigaoxiang** [comment]
when load data images is not normalized indeed
class ResizeNormalize(object):

    def __init__(self, size, interpolation=Image.BICUBIC):
        self.size = size
        self.interpolation = interpolation
        self.toTensor = transforms.ToTensor()

    def __call__(self, img):
        img = img.resize(self.size, self.interpolation)
        img = self.toTensor(img)
        img.sub_(0.5).div_(0.5)
        return img

class NormalizePAD(object):

    def __init__(self, max_size, PAD_type='right'):
        self.toTensor = transforms.ToTensor()
        self.max_size = max_size
        self.max_width_half = math.floor(max_size[2] / 2)
        self.PAD_type = PAD_type

    def __call__(self, img):
        img = self.toTensor(img)
        img.sub_(0.5).div_(0.5)
        c, h, w = img.size()
        Pad_img = torch.FloatTensor(*self.max_size).fill_(0)
        Pad_img[:, :, :w] = img  # right pad
        if self.max_size[2] != w:  # add border Pad
            Pad_img[:, :, w:] = img[:, :, w - 1].unsqueeze(2).expand(c, h, self.max_size[2] - w)

        return Pad_img

**Comment by Sayyam-Jain** [comment]
> can you tell where the code is ,i can not find it ,thank you

https://github.com/clovaai/deep-text-recognition-benchmark/blob/8920de93e8f85e9ddcdf117d256b28ccf8ab4d09/dataset.py#L252

**Comment by FrisaSZ** [comment]
A year has passed, but in order to avoid other people having the same question

[https://pytorch.org/docs/stable/torchvision/transforms.html#torchvision.transforms.ToTensor](https://pytorch.org/docs/stable/torchvision/transforms.html#torchvision.transforms.ToTensor)
> Converts a PIL Image or numpy.ndarray (H x W x C) in the range [0, 255] to a torch.FloatTensor of shape (C x H x W) in the range [0.0, 1.0]

**Comment by JadeKim042386** [comment]
why convert image to range [-1,1]?
