### ISSUE TITLE
Train on handwritten text

### ISSUE THREAD

**Issue by oles-rb** [clovaai/deep-text-recognition-benchmark#135]
Hi
I'm new to neural networks. I need to recognize such pictures
![1](https://user-images.githubusercontent.com/9093474/71804237-92c15880-306b-11ea-9d89-91d6ac32d9cd.jpg)

![2](https://user-images.githubusercontent.com/9093474/71804244-9523b280-306b-11ea-983b-c466b9510346.jpg)

What do I need to train a neural network-single letters or a whole words?

**Comment by ku21fan** [comment]
Hello, 

Follow [this step](https://github.com/clovaai/deep-text-recognition-benchmark#when-you-need-to-train-on-your-own-dataset-or-non-latin-language-datasets ) :)

Best

**Comment by oles-rb** [comment]
Thanks, i got it
I executed `create_lmdb_dataset.py`
Then I run without GPU 
`python train.py \
--train_data data_lmdb_release/training --valid_data data_lmdb_release/validation \
--select_data MJ-ST --batch_ratio 0.5-0.5 \
--Transformation TPS --FeatureExtraction ResNet --SequenceModeling BiLSTM --Prediction Attn`

I get an error

> dataset_root:    C:\\Python\\clovaai\\data_lmdb_release\\training        dataset: MJ
> sub-directory:  /MJ\MJ_test      num samples: 891924
> sub-directory:  /MJ\MJ_train     num samples: 7224586
> sub-directory:  /MJ\MJ_valid     num samples: 802731
> num total samples of MJ: 8919241 x 1.0 (total_data_usage_ratio) = 8919241
> num samples of MJ per batch: 192 x 0.5 (batch_ratio) = 96
> Traceback (most recent call last):
>   File "train.py", line 315, in <module>
>     train(opt)
>   File "train.py", line 31, in train
>     train_dataset = Batch_Balanced_Dataset(opt)
>   File "C:\Python\clovaai\deep_text\dataset.py", line 69, in __init__
>     self.dataloader_iter_list.append(iter(_data_loader))
>   File "C:\Users\talla\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data\dataloader.py", line 278, in __iter__
>     return _MultiProcessingDataLoaderIter(self)
>   File "C:\Users\talla\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data\dataloader.py", line 682, in __init__
>     w.start()
>   File "C:\Users\talla\AppData\Local\Programs\Python\Python37\lib\multiprocessing\process.py", line 112, in start
>     self._popen = self._Popen(self)
>   File "C:\Users\talla\AppData\Local\Programs\Python\Python37\lib\multiprocessing\context.py", line 223, in _Popen
>     return _default_context.get_context().Process._Popen(process_obj)
>   File "C:\Users\talla\AppData\Local\Programs\Python\Python37\lib\multiprocessing\context.py", line 322, in _Popen
>     return Popen(process_obj)
>   File "C:\Users\talla\AppData\Local\Programs\Python\Python37\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
>     reduction.dump(process_obj, to_child)
>   File "C:\Users\talla\AppData\Local\Programs\Python\Python37\lib\multiprocessing\reduction.py", line 60, in dump
>     ForkingPickler(file, protocol).dump(obj)
> TypeError: can't pickle Environment objects
> 
> C:\Python\clovaai\deep_text>Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "C:\Users\talla\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
>     exitcode = _main(fd)
>   File "C:\Users\talla\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 115, in _main
>     self = reduction.pickle.load(from_parent)
> EOFError: Ran out of input

I do not understand what is the reason

Thanks

**Comment by ku21fan** [comment]
That's the problem that occurs when you run the code with Windows OS.
check this issue https://github.com/clovaai/deep-text-recognition-benchmark/issues/17

https://github.com/clovaai/deep-text-recognition-benchmark/blob/24749cd1a3e373a9e3180aa60b6d87ec4d621511/train.py#L234
change `default=4` to `default=0` in this line.

Best

**Comment by oles-rb** [comment]
Thanks for your great work.
