### ISSUE TITLE
change 'align_corner' to 'align_corners' in F.grid_sample() function

### ISSUE THREAD

**Issue by vishaljainai** [clovaai/deep-text-recognition-benchmark#138]
https://github.com/clovaai/deep-text-recognition-benchmark/blob/78d7ed96a93c7472e50480437731f9f37c7b5727/modules/transformation.py#L35

Refer - https://pytorch.org/docs/stable/nn.functional.html#grid-sample

**Comment by ku21fan** [comment]
Hello

Thank you for the report! I just edited it :D

Best
