### ISSUE TITLE
CONCLUSION

### ISSUE THREAD

**Issue by intgogo** [clovaai/deep-text-recognition-benchmark#144]
1.Very good summarize(Transformation, FeatureExtraction, SequenceModeling, Prediction)
2.Some fatal mistakes(slower speed,lower accuracy)
Hahaaa

**Comment by ku21fan** [comment]
Hello, 

1. Thanks.
2. Could you let us know which are `Some fatal mistakes(slower speed,lower accuracy)`?

I close this issue since the title and contents are not appropriate for 'issue'  and wait for your report.

Best
