### ISSUE TITLE
Not able to fine-tune characters that its length is longer than 64

### ISSUE THREAD

**Issue by khanhnt** [clovaai/deep-text-recognition-benchmark#145]
Hi @ku21fan, Thank you for your work. 

I have tried to fine-tune the case sensitive model with my own characters (non-latin one). But when the character list has more than 64 char, i get the following errors:
`Traceback (most recent call last):
  
File "train.py", line 332, in <module>
    train(opt)
  File "train.py", line 82, in train
    model.load_state_dict(torch.load(opt.saved_model), strict=False)
  File "/home/khanhnt/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 839, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DataParallel:
	size mismatch for module.Prediction.attention_cell.rnn.weight_ih: copying a param with shape torch.Size([1024, 352]) from checkpoint, the shape in current model is torch.Size([1024, 353]).
	size mismatch for module.Prediction.generator.weight: copying a param with shape torch.Size([96, 256]) from checkpoint, the shape in current model is torch.Size([97, 256]).
	size mismatch for module.Prediction.generator.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([97]).
`
Here is the command I have used to fine-tune:

`CUDA_VISIBLE_DEVICES=0 python3 train.py --train_data result/train_27022020/train/ --valid_data result/train_27022020/valid/ --Transformation TPS --FeatureExtraction ResNet --SequenceModeling BiLSTM --Prediction Attn  --sensitive --FT --saved_model model/TPS-ResNet-BiLSTM-Attn-case-sensitive_15000.pth --batch_size 82`

I have tried several solution that you and the others recommended, for examle [(Load with model.load_state_dict(torch.load(opt.saved_model), strict=False))](https://github.com/clovaai/deep-text-recognition-benchmark/issues/73#issuecomment-535858700); [make character list file](https://github.com/clovaai/deep-text-recognition-benchmark/issues/85#issuecomment-538889138) but non of them can make it work. Do you have any recommendation for me. Do I need to retrain the model from scraft ?
 Thank a lot.

**Comment by khanhnt** [comment]
Loading model without prediction layer or loading full model and initiating new prediction layer with saved configurations (rnn, weight, bias) will fix the issue

**Comment by iknoorjobs** [comment]
Hi @khanhnt 

How were you able to solve this problem? I am facing similar issue for non-latin fine tuning.

I am trying to fine-tune the normal case insensitive model (TPS-ResNet-BiLSTM-Attn) by running the following command. I have also added 4 additional characters to opt.character

`CUDA_VISIBLE_DEVICES=0 python3 train.py --train_data result/train --valid_data result/valid --select_data / --batch_ratio 1 --Transformation TPS --FeatureExtraction ResNet --SequenceModeling BiLSTM --Prediction Attn --FT --saved_model TPS-ResNet-BiLSTM-Attn_15000.pth
`

It's showing the following error. 

![Annotation 2020-09-26 092128](https://user-images.githubusercontent.com/22852967/94329575-d1bc8300-ffd9-11ea-86c1-c08ae40a5806.jpg)

Thanks for help.

Iknoor
