### ISSUE TITLE
How to fine tune train.py on own dataset?

### ISSUE THREAD

**Issue by hhaahaha** [clovaai/deep-text-recognition-benchmark#146]
Thank you for your nice work,
I have my own dataset. After pre-train MJ/ST synth data set, How can I fine tune train.py?

**Comment by hhaahaha** [comment]
I find the way. 
Just add --FT command at terminal with your own dataset which created from 'create_lmdb_dataset.py'!

**Comment by zcswdt** [comment]
> I find the way.
> Just add --FT command at terminal with your own dataset which created from 'create_lmdb_dataset.py'!

请问你在训练的时候加了rgb和pad这两个参数吗

**Comment by macqueen09** [comment]
Can pre-training models be used even if the categories are slightly different?
