### ISSUE TITLE
Do you have any plans to release the pretrained model on ICDAR2019 ReCTS (task1)?

### ISSUE THREAD

**Issue by bityigoss** [clovaai/deep-text-recognition-benchmark#15]

**Comment by ku21fan** [comment]
Hello, 

We didn't have the plan to release that model.
Thus, we are going to discuss whether or not to release it.
Probably we will notify about it during next week.

Best,
Baek.

**Comment by ku21fan** [comment]
@bityigoss 
This repository shares the traditional modules that are widely used in STR tasks and provide an STR model in the paper. 
So, I’m afraid that we let you know the pre-trained model for Chinese is not be provided because the model has some additional features for Chinese which are not in our paper.

Best

**Comment by bityigoss** [comment]
@ku21fan Thanks for your replay and sharing your awesome works
I'm  trying to use this framework to train Chinese-models, can you give me some advice or tricks ? Did you also use synthetic data for training/validating the model for Chinese ?
Thank you very much.
best

**Comment by ku21fan** [comment]
@bityigoss 
Yes, we used public real dataset and synthetic dataset for training/validating the model for Chinese.
Chinese dataset usually has some vertical dataset, thus generating vertical text data would be helpful :)

**Comment by zhengjiawen** [comment]
> @bityigoss
> Yes, we used public real dataset and synthetic dataset for training/validating the model for Chinese.
> Chinese dataset usually has some vertical dataset, thus generating vertical text data would be helpful :)

Hi, thanks for your sharing code. I want to train Chinese model, could you tell me which good synthetic Chinese data sets or methods for generating synthetic Chinese data sets? 
Thanks a lot.
