### ISSUE TITLE
show a question when training

### ISSUE THREAD

**Issue by 1407heanhua** [clovaai/deep-text-recognition-benchmark#156]
Hi,
I ran train.py,but I got a error as shown:
![image](https://user-images.githubusercontent.com/38280262/79290393-93854880-7efe-11ea-88d3-5f998b0cb719.png)
Can you help me reslove this?

**Comment by 1407heanhua** [comment]
torch version 1.2.0
cuda  version 10.1 
python 3.6.8

**Comment by 1407heanhua** [comment]
已解决，解决方法，将torch升级为1.4.0

**Comment by zcswdt** [comment]
> 已解决，解决方法，将torch升级为1.4.0

哈喽，我也在训练遇到了点问题，可以交流一下吗？
