### ISSUE TITLE
miss match in size

### ISSUE THREAD

**Issue by GSATHYANARAYANA** [clovaai/deep-text-recognition-benchmark#16]
RuntimeError: Error(s) in loading state_dict for DataParallel:
	size mismatch for module.Prediction.attention_cell.rnn.weight_ih: copying a param with shape torch.Size([1024, 352]) from checkpoint, the shape in current model is torch.Size([1024, 294]).
	size mismatch for module.Prediction.generator.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([38]).
	size mismatch for module.Prediction.generator.weight: copying a param with shape torch.Size([96, 256]) from checkpoint, the shape in current model is torch.Size([38, 256]).

**Comment by ku21fan** [comment]
Hello, 

I guess you were trying to use case-sensitive pretrained model.
If you use case-sensitive model, you should add `--sensitive` option.
Please try with it.

Best

**Comment by GSATHYANARAYANA** [comment]
assert len(datasets) > 0, 'datasets should not be an empty iterable'
AssertionError: datasets should not be an empty iterable

**Comment by ku21fan** [comment]
This message usually occurs when the dataset was not specified or empty.
Thus, please check the dataset path. 

Or, did you test with your own dataset? 
If you do so, there are 2 way to test your own dataset.

1. make your dataset into lmdb dataset first (see [here](https://github.com/clovaai/deep-text-recognition-benchmark#when-you-need-to-create-lmdb-dataset)), then add `--eval_data your_evaluation_dataset_path` option

2. use demo.py file (see [here](https://github.com/clovaai/deep-text-recognition-benchmark#run-demo-with-pretrained-model))

Hope it helps :)

**Comment by GSATHYANARAYANA** [comment]
Thanks for the help
If I run the demo.py file than the results will be 
--------------------------------------------------------------------------------
image_path	predicted_labels
--------------------------------------------------------------------------------
{img_name}	{pred}
{img_name}	{pred}
{img_name}	{pred}
{img_name}	{pred}
{img_name}	{pred}
{img_name}	{pred}
{img_name}	{pred}
{img_name}	{pred}
{img_name}	{pred}
{img_name}	{pred}

**Comment by ku21fan** [comment]
Yes, it will be :D

**Comment by NasimSulaiman** [comment]
Hi, 
Even after adding the --sensitive option i am still getting the same error mentioned above, 
RuntimeError: Error(s) in loading state_dict for DataParallel:
	size mismatch for module.Prediction.attention_cell.rnn.weight_ih: copying a param with shape torch.Size([1024, 352]) from checkpoint, the shape in current model is torch.Size([1024, 353]).
	size mismatch for module.Prediction.generator.weight: copying a param with shape torch.Size([96, 256]) from checkpoint, the shape in current model is torch.Size([97, 256]).
	size mismatch for module.Prediction.generator.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([97]).
can you help.

**Comment by amirshafiei96** [comment]
I have same error but when I add --sensitive it doesn't fix

**Comment by amirshafiei96** [comment]
> Hello,
> 
> I guess you were trying to use case-sensitive pretrained model. If you use case-sensitive model, you should add `--sensitive` option. Please try with it.
> 
> Best

I have same error but when I add --sensitive it doesn't fix
