### ISSUE TITLE
Detail webDemo

### ISSUE THREAD

**Issue by MacNgoc** [clovaai/deep-text-recognition-benchmark#162]
Hi,
Thanks for sharing these great works.
I tested my cases on your webDemo, it gives me a good result. 
However, when I clone your project and test the same images, it gives me a bad result. (about 0 conf). 
I found the guide "Combination of Clova AI detection and recognition, additional/advanced features used for KOR/JPN ". But i don't really understand what did you do and why my case is really bad if i just use recognition :)
Could you tell me more about this processing, please? 

Many thanks,

**Comment by ku21fan** [comment]
Hello, 

I’m afraid that we can not answer the detail about them because it is related to our service.

Abstractly, we collected/generated KOR/JPN datasets and trained model with them,
and we used the advanced modules and training techniques.

Best.
