### ISSUE TITLE
about test.py

### ISSUE THREAD

**Issue by zcswdt** [clovaai/deep-text-recognition-benchmark#163]
Thank you for sharing, great work. I have a problem now. When I use your best accuracy to run ic13 data, I encounter the following error, I do n’t know how to solve it, can you give me some pointers? Thank you。
![image](https://user-images.githubusercontent.com/43515926/81366760-05c40400-911e-11ea-800c-ff755e1dc057.png)

**Comment by ku21fan** [comment]
Hello, 

[This comment in the link](https://github.com/clovaai/deep-text-recognition-benchmark/issues/172#issuecomment-639380782) would solve this issue.

Hope it helps,
Best
