### ISSUE TITLE
TypeError: can't pickle Environment objects

### ISSUE THREAD

**Issue by MattHuntebrinker** [clovaai/deep-text-recognition-benchmark#17]
I'm getting this error when trying to train on default data, any information is helpful!

**Comment by MattHuntebrinker** [comment]
It seems that this is a windows specific issue, and has to do with the number of workers > 0. If I set num workers = 0, it runs fine.

**Comment by anavc94** [comment]
> It seems that this is a windows specific issue, and has to do with the number of workers > 0. If I set num workers = 0, it runs fine.

Thanks! Windows is always trolling...
