### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by guangyuchen123** [clovaai/deep-text-recognition-benchmark#171]
When I try to run the demo file on ubuntu python3, the terminal shows: 
 
 File "demo.py", line 71

    log = open(f'./log_demo_result.txt', 'a')

                                      ^

SyntaxError: invalid syntax

Can anyone help me?

**Comment by ku21fan** [comment]
Hello, 

I guess this is a python version issue derived from the `f-string`, which is introduced in `python 3.6`.
So I recommend using the python >= 3.6.

Hope it works

Best
