### ISSUE TITLE
How to train with custom data - AssertionError: datasets should not be an empty iterable

### ISSUE THREAD

**Issue by pendex900x** [clovaai/deep-text-recognition-benchmark#172]
I use this command to train: `!python3 '/content/deep-text-recognition-benchmark/create_lmdb_dataset.py' --inputPath '/content/deep-text-recognition-benchmark/train' --gtFile '/content/gt.txt' --outputPath '/content/deep-text-recognition-benchmark/result'` 
I want to use it to detect license plates.

`Input_path `have inputPath with input images, with names like 'CJFY10,jpg'
`outputPath` it is an empty folder.
`gtFile` it is an txt with this format:
```
C:/Users/X/Desktop/deep-text-recognition-benchmark-master/train/DVHS56.png DVHS56
C:/Users/X/Desktop/deep-text-recognition-benchmark-master/train/DYVS72.png DYVS72
C:/Users/X/Desktop/deep-text-recognition-benchmark-master/val/HDYP18.png HDYP18
C:/Users/X/Desktop/deep-text-recognition-benchmark-master/val/HKHT72.png HKHT72
C:/Users/X/Desktop/deep-text-recognition-benchmark-master/val/HPXC69.png HPXC69
```

And error when I run the command it is:
```
Traceback (most recent call last):
  File "/content/deep-text-recognition-benchmark/create_lmdb_dataset.py", line 87, in <module>
    fire.Fire(createDataset)
  File "/usr/local/lib/python3.6/dist-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.6/dist-packages/fire/core.py", line 468, in _Fire
    target=component.__name__)
  File "/usr/local/lib/python3.6/dist-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/content/deep-text-recognition-benchmark/create_lmdb_dataset.py", line 47, in createDataset
    imagePath, label = datalist[i].strip('\n').split('\t')
ValueError: not enough values to unpack (expected 2, got 1)
```

What I'm doing wrong? Any help is welcome

**Comment by vipin-kunam** [comment]
Make sure your gt file does not contain space in the middle or  at the end.Every line should have path and label seperated by space.

**Comment by pendex900x** [comment]
> Make sure your gt file does not contain space in the middle or at the end.Every line should have path and label seperated by space.This is because a particular line in gt file contains only space.

when it had to be modified this line
`env = lmdb.open(outputPath, map_size=1099511627776)` to this `env = lmdb.open (outputPath, map_size = 10995116277)`

The output was 2 files in result folder, `data.mdb` and `lock.mdb`

 I changed that line because of space problems. Now I'm running that in my local computer and not in Google Colab.

And also I did this 1 step of this [link] by ku21fan (https://github.com/clovaai/deep-text-recognition-benchmark/issues/85) except the last one of 

> you should change opt.character into your own character list

And now when I trying to run: `python train.py --train_data 'C:/Users/X/Desktop/deep-text-recognition-benchmark-master/train' --valid_data 'C:/Users/X/Desktop/deep-text-recognition-benchmark-master/val' --Transformation TPS --FeatureExtraction ResNet --SequenceModeling BiLSTM --Prediction Attn`

But the output is:

```
Filtering the images containing characters which are not in opt.character
Filtering the images whose label is longer than opt.batch_max_length
--------------------------------------------------------------------------------
dataset_root: 'C:/Users/X/Desktop/deep-text-recognition-benchmark-master/train'
opt.select_data: ['/']
opt.batch_ratio: ['1']
--------------------------------------------------------------------------------
dataset_root:    'C:/Users/X/Desktop/deep-text-recognition-benchmark-master/train'       dataset: /
Traceback (most recent call last):
  File "train.py", line 314, in <module>
    train(opt)
  File "train.py", line 31, in train
    train_dataset = Batch_Balanced_Dataset(opt)
  File "C:\Users\X\Desktop\deep-text-recognition-benchmark-master\dataset.py", line 42, in __init__
    _dataset, _dataset_log = hierarchical_dataset(root=opt.train_data, opt=opt, select_data=[selected_d])
  File "C:\Users\X\Desktop\deep-text-recognition-benchmark-master\dataset.py", line 124, in hierarchical_dataset
    concatenated_dataset = ConcatDataset(dataset_list)
  File "C:\Users\X\Anaconda3\lib\site-packages\torch\utils\data\dataset.py", line 68, in __init__
    assert len(datasets) > 0, 'datasets should not be an empty iterable'
AssertionError: datasets should not be an empty iterable
```
Why this error happends? **AssertionError: datasets should not be an empty iterable**

**Comment by ku21fan** [comment]
Hello, 

1) the image path and labels should be separated with 'tab'
`{imagepath}\t{label}\n`
\t means 'tab'

So I recommend replacing `.png ` (.png + space) with `.png\t` (.png + tab) in your gt file.

2) AssertionError: datasets should not be an empty iterable
-> this error occurs when the lmdb dataset is empty.
so, if you succeed to create the lmdb dataset, it would be also solved.

Hope it helps,
Best

**Comment by lvforce** [comment]
> Hello @ku21fan,
> 
> I have followed your instructions and changed the gt file to follow the format `{imagepath}\t{label}\n` however, I am still facing the AssertionError. Is there anyway to check if the lmdb dataset is created properly?
> 
> I am currently trying to train the model on Thai. I have changed the character list as follows:
> 
> ![image](https://user-images.githubusercontent.com/90379470/139395388-a4a9e7f0-a466-4989-97dc-057c3f668d4d.png)
> 
> and also updated `--select_data` and `--batch_ratio` as follows:
> 
> ![image](https://user-images.githubusercontent.com/90379470/139395494-f7851cf4-ee9f-4850-8d87-40af9ce2f6aa.png)
> 
> but I am still facing the same error when I try to train using the command `train.py --train_data train/result/data.mdb --valid_data validation/result/data.mdb --Transformation None --FeatureExtraction VGG --SequenceModeling BiLSTM --Prediction CTC --data_filtering_off`
> 
> ![image](https://user-images.githubusercontent.com/90379470/139396010-945da482-969e-4969-9782-ff586b114499.png)
> 
> Is there anything I am missing out?

did you resolve it?

**Comment by 678098** [comment]
So I've encountered the same problem. It looks like `train.py` args like `--select_data` and `--batch_ratio` are needed to be set together to some value to not filter out directories with some names.

So if you have `train` directory, you can specify `--select_data train --batch_ratio 0.5` to make it work.

**Comment by bilalltf** [comment]
I'm facing the same issue did anyone resolve it?

**Comment by TheChwal** [comment]
Same issue here

**Comment by MauroLeidi** [comment]
Maybe you have a blank line at the end if you are using pandas.to_csv(separator = '\t') function. You should remove any blank line at the end of the file  (\n alone in the last line)

**Comment by Vaibhavsun** [comment]
Has anyone find solution for datasets should not be any empty  iterable

**Comment by MazetDev** [comment]
Same issue here

**Comment by S0mbre** [comment]
Same here. Issue remains.
