### ISSUE TITLE
How to train custom data after creating mdb files.

### ISSUE THREAD

**Issue by pendex900x** [clovaai/deep-text-recognition-benchmark#174]
I finally create `data.mdb` and `lock.mdb` with this command:

`!python '/content/drive/My Drive/deep-text-recognition-benchmark-1/create_lmdb_dataset.py' --inputPath '/content/drive/My Drive/deep-text-recognition-benchmark-1/train' --gtFile '/content/drive/My Drive/deep-text-recognition-benchmark-1/gt.txt' --outputPath '/content/drive/My Drive/deep-text-recognition-benchmark-1/result'`

Now I have to use another command to start training:

`!python '/content/drive/My Drive/deep-text-recognition-benchmark-1/train.py' --train_data '/content/deep-text-recognition-benchmark-1/train' --valid_data '/content/deep-text-recognition-benchmark-1/val' --Transformation TPS --FeatureExtraction ResNet --SequenceModeling BiLSTM --Prediction Attn --select_data '/content/drive/My Drive/deep-text-recognition-benchmark-1/result'`

But if I use this command the output will be:

```
Filtering the images containing characters which are not in opt.character
Filtering the images whose label is longer than opt.batch_max_length
--------------------------------------------------------------------------------
dataset_root: /content/deep-text-recognition-benchmark-1/train
opt.select_data: ['/content/drive/My Drive/deep', 'text', 'recognition', 'benchmark', '1/result']
opt.batch_ratio: ['1']
Traceback (most recent call last):
  File "/content/drive/My Drive/deep-text-recognition-benchmark-1/train.py", line 315, in <module>
    train(opt)
  File "/content/drive/My Drive/deep-text-recognition-benchmark-1/train.py", line 31, in train
    train_dataset = Batch_Balanced_Dataset(opt)
  File "/content/drive/My Drive/deep-text-recognition-benchmark-1/dataset.py", line 31, in __init__
    assert len(opt.select_data) == len(opt.batch_ratio)
AssertionError
```

And if I use this command without --select_data like this:

`!python '/content/drive/My Drive/deep-text-recognition-benchmark-1/train.py' --train_data '/content/deep-text-recognition-benchmark-1/train' --valid_data '/content/deep-text-recognition-benchmark-1/val' --Transformation TPS --FeatureExtraction ResNet --SequenceModeling BiLSTM --Prediction Attn`

The output will be:

```
Filtering the images containing characters which are not in opt.character
Filtering the images whose label is longer than opt.batch_max_length
--------------------------------------------------------------------------------
dataset_root: /content/deep-text-recognition-benchmark-1/train
opt.select_data: ['/']
opt.batch_ratio: ['1']
--------------------------------------------------------------------------------
dataset_root:    /content/deep-text-recognition-benchmark-1/train	 dataset: /
Traceback (most recent call last):
  File "/content/drive/My Drive/deep-text-recognition-benchmark-1/train.py", line 315, in <module>
    train(opt)
  File "/content/drive/My Drive/deep-text-recognition-benchmark-1/train.py", line 31, in train
    train_dataset = Batch_Balanced_Dataset(opt)
  File "/content/drive/My Drive/deep-text-recognition-benchmark-1/dataset.py", line 42, in __init__
    _dataset, _dataset_log = hierarchical_dataset(root=opt.train_data, opt=opt, select_data=[selected_d])
  File "/content/drive/My Drive/deep-text-recognition-benchmark-1/dataset.py", line 124, in hierarchical_dataset
    concatenated_dataset = ConcatDataset(dataset_list)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataset.py", line 188, in __init__
    assert len(datasets) > 0, 'datasets should not be an empty iterable'
AssertionError: datasets should not be an empty iterable
```

There is a train folder with 6 images.
There is a val folder but it's empty, is it ok? also have made things from this [link](https://github.com/clovaai/deep-text-recognition-benchmark/issues/85) What I'm doing wrong??

**Comment by ku21fan** [comment]
Sorry for the late reply, 
I reply to https://github.com/clovaai/deep-text-recognition-benchmark/issues/172#issuecomment-639380782 
Please check and if the problem was not solved, comment on that issue.

I will close this issue since it seems duplicate.

Best

**Comment by pendex900x** [comment]
Thanks for your reply,

`opt.select_data: ['/']` means that in '/' will be the `.mdb` files?
Then I got the .mdb files (data.mdb and lock.mdb) 

`opt.select_data` refers to those files?

**Comment by ku21fan** [comment]
`opt.select_data: ['/']` means 'use all dataset under `--train_data` folder'.

default is `opt.select_data: MJ-ST` which means 'use MJ and ST datasets under `--train_data` folder'.

You can check the structure of the `--train_data` folder in [here](https://drive.google.com/drive/folders/192UfE9agQUMNq6AgU3_E05_FcPZK4hyt).

```
data_lmdb_release
└──training
      └──MJ
          └── MJ_train
              ├── data.mdb
              └── lock.mdb
          └── MJ_valid
              ├── data.mdb
              └── lock.mdb
          └── MJ_test
              ├── data.mdb
              └── lock.mdb
```

**Comment by Sakshisaxena04** [comment]
Hi, I have created same structure as discussed above:
data_lmdb_release
└──training
      └──data
          └── data_train
              ├── data.mdb
              └── lock.mdb
          └── data_valid
              ├── data.mdb
              └── lock.mdb
          └──data_test
              ├── data.mdb
              └── lock.mdb

Using training command as :
python train.py --train_data data_lmdb_release/training/ data/data_train --valid_data data_lmdb_release/training/data/data_valid --select_data data --batch_ratio 0.5-0.5 --Transformation TPS --FeatureExtraction ResNet --SequenceModeling BiLSTM --Prediction Attn



But getting error:
/mnt/vol1/testing_anaconda3/envs/test_TR/lib/python3.6/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 10010). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
Filtering the images containing characters which are not in opt.character
Filtering the images whose label is longer than opt.batch_max_length
--------------------------------------------------------------------------------
dataset_root: data_lmdb_release/training/data/data_train
opt.select_data: ['data']
opt.batch_ratio: ['0.5', '0.5']
Traceback (most recent call last):
  File "train.py", line 317, in <module>
    train(opt)
  File "train.py", line 31, in train
    train_dataset = Batch_Balanced_Dataset(opt)
  File "/mnt/vol1/sakshi/deep-text-recognition-benchmark-master/dataset.py", line 31, in __init__
    assert len(opt.select_data) == len(opt.batch_ratio)
AssertionError



please suggest

**Comment by chirico85** [comment]
To comment on the original question:
I ran into the same problem and found out while debugging that filtering of my training data resulted into nSamples = 0.
Either you change the batch_max_length to a length lower than your minimal data length and so on.. Or you just add  --data_filtering_off to your command.

**Comment by mohamedabdallah1996** [comment]
@chirico85  Thank you so much. this solved my issue
