### ISSUE TITLE
num samples of train and test data less than the real num

### ISSUE THREAD

**Issue by wolfryu** [clovaai/deep-text-recognition-benchmark#187]
I prepared training data 3500000, test data 113.
After start training, log shows:
--------------------------------------------------------------------------------
dataset_root:    result/train360         dataset: /
sub-directory:  /.       num samples: 2989400
num total samples of /: 2989400 x 1.0 (total_data_usage_ratio) = 2989400
num samples of / per batch: 192 x 1.0 (batch_ratio) = 192
--------------------------------------------------------------------------------
Total_batch_size: 192 = 192
--------------------------------------------------------------------------------
dataset_root:    result/test2    dataset: /
sub-directory:  /.       num samples: 110
--------------------------------------------------------------------------------

3500000 becomes 2989400 , 113 becomes 110, why this happens?

**Comment by 2113vm** [comment]
It can be helpful
https://github.com/clovaai/deep-text-recognition-benchmark/issues/186

**Comment by wolfryu** [comment]
@2113vm thank you so much!
