### ISSUE TITLE
Can't run demo on custom trained unicode-character datasets

### ISSUE THREAD

**Issue by hungtooc** [clovaai/deep-text-recognition-benchmark#193]
Hi. 
I have trained my dataset with vietnamese character: 

> '0123456789aáàạãảăắằẳẵặâấầẩẫậbcdđeéèểẽẹêếềểễệfghiíìỉĩịjklmnoóòỏõọôốồổỗộơớờởỡợpqrstuúùủũụưứừửũựvwxyýỳỷỹỵz',

by follwing command:
```
!CUDA_VISIBLE_DEVICES=0 python3 train.py \
--train_data /content/training --valid_data /content/testing \
--Transformation TPS --FeatureExtraction ResNet --SequenceModeling BiLSTM --Prediction Attn
```
Then i tested model by following command with using my trained file .pth:
```
!CUDA_VISIBLE_DEVICES=0 python3 demo.py \
--sensitive \
--Transformation TPS \
--FeatureExtraction ResNet \
--SequenceModeling BiLSTM \
--Prediction Attn \
--image_folder /content/deep-text-recognition-benchmark/demo_image \
--saved_model /content/deep-text-recognition-benchmark/saved_models/TPS-ResNet-BiLSTM-Attn-Seed1111/best_accuracy.pth
```
The result have failed with errors:
```model input parameters 32 100 20 1 512 256 96 25 TPS ResNet BiLSTM Attn
loading pretrained model from /content/deep-text-recognition-benchmark/saved_models/TPS-ResNet-BiLSTM-Attn-Seed1111/best_accuracy.pth
Traceback (most recent call last):
  File "demo.py", line 130, in <module>
    demo(opt)
  File "demo.py", line 34, in demo
    model.load_state_dict(torch.load(opt.saved_model, map_location=device))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 847, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DataParallel:
	size mismatch for module.Prediction.attention_cell.rnn.weight_ih: copying a param with shape torch.Size([1024, 361]) from checkpoint, the shape in current model is torch.Size([1024, 352]).
	size mismatch for module.Prediction.generator.weight: copying a param with shape torch.Size([105, 256]) from checkpoint, the shape in current model is torch.Size([96, 256]).
	size mismatch for module.Prediction.generator.bias: copying a param with shape torch.Size([105]) from checkpoint, the shape in current model is torch.Size([96]).```
How can i fix the problem? Thanks.

**Comment by Tamoghna-Saha** [comment]
Your `opt.character` needs to be changed. By default, it is still accessing the English letters.
If possible, hardcode the `opt.character` variable in the script, and run without the `--sensitive` argument while executing.

**Comment by Rhcsky** [comment]
Have you done applied your character? When you train your own dataset, you should apply your character on model. 
The command you write is trained about English and number. The opt.character default is '123456789abcdefghijklmnopqrstuvwxyz' So you can train your data  correctly by changing the `opt.character` from English+number to Vietnamese character. And turn off `--sensitive` option, it is not suitable for your charter.

The way to apply Vietnamese character to opt.character is simple. In `train.py`, just write this on `if __name__ == '__main__':`
```python
opt.character = '0123456789aáàạãảăắằẳẵặâấầẩẫậbcdđeéèểẽẹêếềểễệfghiíìỉĩịjklmnoóòỏõọôốồổỗộơớờởỡợpqrstuúùủũụưứừửũựvwxyýỳỷỹỵz',
```

**Comment by ThanhNhann** [comment]
Sorry for this comment, but have you done training  in VietNamess dataset @hungtooc

**Comment by viethungtsdv** [comment]
Hi @Rhcsky 
Thanks you for your suggestion.
I also fine-tuning with vietnamese, however I meet issue with CTC loss as below:
"cost = tensor(nan, device='cuda:0', grad_fn=<MeanBackward1>)"
-> The cost value is "nan". (I am using torch version 1.5.0)

Could you please support me?

Best regards,
