### ISSUE TITLE
demo error with pretrained CTC models?

### ISSUE THREAD

**Issue by janetwise** [clovaai/deep-text-recognition-benchmark#198]
I'm able to run the demo with the pretrained Attn model as shown.
CUDA_VISIBLE_DEVICES=0 python3 demo.py \
--Transformation TPS --FeatureExtraction ResNet --SequenceModeling BiLSTM --Prediction Attn \
--image_folder demo_image/ \
--saved_model TPS-ResNet-BiLSTM-Attn.pth

However when I tried to use your other pretrained CTC models, got the same error for all the other 4 CTC models:

python demo.py --image_folder demo_image/bak --saved_model models/TPS-ResNet-BiLSTM-CTC.pth --Transformation TPS --FeatureExtraction ResNet --SequenceModeling BiLSTM --Prediction CTC
model input parameters 32 100 20 1 512 256 37 25 TPS ResNet BiLSTM CTC
loading pretrained model from models/TPS-ResNet-BiLSTM-CTC.pth
Traceback (most recent call last):
  File "demo.py", line 129, in <module>
    demo(opt)
  File "demo.py", line 61, in demo
    preds_str = converter.decode(preds_index.data, preds_size.data)
  File "/cto-home/gmpn67/DeepLearning/deep-text-recognition-benchmark/utils.py", line 43, in decode
    t = text_index[index, :]
IndexError: too many indices for tensor of dimension 1

**Comment by Rhcsky** [comment]
Give it a try to **comment out** the line 60 in `demo.py`
```python
preds_index = preds_index.view(-1)
```

**Comment by janetwise** [comment]
> Give it a try to **comment out** the 60th line in `demo.py`
> 
> ```python
> preds_index = preds_index.view(-1)
> ```

Worked! Thanks a lot!!

**Comment by gwkrsrch** [comment]
resolved by 7f59fb0
