### ISSUE TITLE
Training and testing on custom data

### ISSUE THREAD

**Issue by TsainGra** [clovaai/deep-text-recognition-benchmark#2]
How can I train and test these models on my own data?

**Comment by ku21fan** [comment]
Hello, @TsainGra 
At first, make the lmdb datasets with your own data. 
You can make lmdb datasets with [this script](https://github.com/clovaai/deep-text-recognition-benchmark#when-you-need-to-create-lmdb-dataset)
After that, train and test with those lmdb datasets, as follows.
Train
```
CUDA_VISIBLE_DEVICES=0 python3 train.py \
--train_data {your train lmdb} --valid_data {your valid lmdb} --select_data / --batch_ratio 1 \
--Transformation TPS --FeatureExtraction ResNet --SequenceModeling BiLSTM --Prediction Attn
```
Test 
```
CUDA_VISIBLE_DEVICES=0 python3 test.py \
--eval_data {your test lmdb} \
--Transformation TPS --FeatureExtraction ResNet --SequenceModeling BiLSTM --Prediction Attn \
--saved_model saved_models/TPS-ResNet-BiLSTM-Attn-Seed1111/best_accuracy.pth
```

Best.

**Comment by TsainGra** [comment]
Thanks, this works.

**Comment by TsainGra** [comment]
Let's say I want to include more characters (including special) what steps do I need to take. If I edit the default value in --character (I am including " /,.:-<&()#;" character. This shows the following error -
[0/300000] Loss: 99.97011 elapsed_time: 2.57278
Traceback (most recent call last):
  File "train.py", line 278, in <module>
    train(opt)
  File "train.py", line 162, in train
    model, criterion, valid_loader, converter, opt)
  File "/mnt/kushagra/deep-text-recognition-benchmark/test.py", line 74, in validation
    for i, (cpu_images, cpu_texts) in enumerate(evaluation_loader):
  File "/home/tsaingra/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 623, in __next__
    return self._process_next_batch(batch)
  File "/home/tsaingra/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
ValueError: Traceback (most recent call last):
  File "/home/tsaingra/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/mnt/kushagra/deep-text-recognition-benchmark/dataset.py", line 185, in __call__
    images, labels = zip(*batch)
ValueError: not enough values to unpack (expected 2, got 0)
I printed the batch and the entire batch was [None] earlier batches contained tuples.

**Comment by ku21fan** [comment]
Your step was right, edit the argument '--character' for additional characters.
In this case,  `--characters 0123456789abcdefghijklmnopqrstuvwxyz/,.:-<&()#;`

I guess that error msg occurs when validation data was none or something.
Could you check validation data or share the part of log when running train.py? 
Especially this part.

```
--------------------------------------------------------------------------------
dataset_root: data_lmdb_release/training
opt.select_data: ['MJ', 'ST']
opt.batch_ratio: ['0.5', '0.5']
--------------------------------------------------------------------------------
dataset_root:    data_lmdb_release/training      dataset: MJ
sub-directory:  /MJ/MJ_valid     num samples: 802731
sub-directory:  /MJ/MJ_test      num samples: 891924
sub-directory:  /MJ/MJ_train     num samples: 7224586
num total samples of MJ: 8919241 x 1.0 (total_data_usage_ratio) = 8919241
num samples of MJ per batch: 192 x 0.5 (batch_ratio) = 96
--------------------------------------------------------------------------------
dataset_root:    data_lmdb_release/training      dataset: ST
sub-directory:  /ST      num samples: 5522808
num total samples of ST: 5522808 x 1.0 (total_data_usage_ratio) = 5522808
num samples of ST per batch: 192 x 0.5 (batch_ratio) = 96
--------------------------------------------------------------------------------
Total_batch_size:  96+96 = 192
--------------------------------------------------------------------------------
dataset_root:    data_lmdb_release/validation    dataset: /
sub-directory:  /.       num samples: 6992
--------------------------------------------------------------------------------
```

**Comment by TsainGra** [comment]
Hey, that issue was resolved, it happened because I tried to load color images in grayscale, resolved that. Now facing issue with ctc. Do I need to include space " " in the character string?
PS- I have edited the issue.

**Comment by ku21fan** [comment]
> Do I need to include space " " in the character string?

No, you don't need to include " ", when you use the CTC loss, [a blank token is added to](https://github.com/clovaai/deep-text-recognition-benchmark/blob/master/utils.py#L9) characters by default.

**Comment by iknoorjobs** [comment]
> Hello, @TsainGra
> At first, make the lmdb datasets with your own data.
> You can make lmdb datasets with [this script](https://github.com/clovaai/deep-text-recognition-benchmark#when-you-need-to-create-lmdb-dataset)
> After that, train and test with those lmdb datasets, as follows.
> Train
> 
> ```
> CUDA_VISIBLE_DEVICES=0 python3 train.py \
> --train_data {your train lmdb} --valid_data {your valid lmdb} --select_data / --batch_ratio 1 \
> --Transformation TPS --FeatureExtraction ResNet --SequenceModeling BiLSTM --Prediction Attn
> ```
> 
> Test
> 
> ```
> CUDA_VISIBLE_DEVICES=0 python3 test.py \
> --eval_data {your test lmdb} \
> --Transformation TPS --FeatureExtraction ResNet --SequenceModeling BiLSTM --Prediction Attn \
> --saved_model saved_models/TPS-ResNet-BiLSTM-Attn-Seed1111/best_accuracy.pth
> ```
> 
> Best.

Hi @ku21fan @TsainGra 

I just tried on my custom data (lmdb format) by running the command

`CUDA_VISIBLE_DEVICES=0 python3 train.py --train_data result/train --valid_data result/valid --select_data / --batch_ratio 1 --Transformation TPS --FeatureExtraction ResNet --SequenceModeling BiLSTM --Prediction Attn`

But after 1st iteration i.e.
................
num_gpu: 1
num_class: 38
---------------------------------------

[1/300000] Train loss: 3.65088, Valid loss: 3.67733, Elapsed_time: 2.56574
Current_accuracy : 0.000, Current_norm_ED  : 0.01
Best_accuracy    : 0.000, Best_norm_ED     : 0.01
--------------------------------------------------------------------------------
Ground Truth              | Prediction                | Confidence Score & T/F
--------------------------------------------------------------------------------
.................... 
...............

Nothing happens afterwards. Could you please help to tell what may be the possible reasons?

Thanks
Iknoor

**Comment by lambdaterm** [comment]
Hi, @iknoorjobs 

Probably you need to wait more time because the default `train.py` doesn't prints log on each iteration. See https://github.com/clovaai/deep-text-recognition-benchmark/blob/master/train.py#L175

**Comment by iknoorjobs** [comment]
> Hi, @iknoorjobs
> 
> Probably you need to wait more time because the default `train.py` doesn't prints log on each iteration. See https://github.com/clovaai/deep-text-recognition-benchmark/blob/master/train.py#L175

Hi 
Thanks :) Got it.
But I wonder why it's taking so much time on GPU. I only provided 10 images for training.
