### ISSUE TITLE
Unexpected key(s) in state_dict

### ISSUE THREAD

**Issue by MattHuntebrinker** [clovaai/deep-text-recognition-benchmark#20]
After training my model, i'm having trouble testing my model on images. I'm getting this error message 

RuntimeError: Error(s) in loading state_dict for DataParallel:
        Missing key(s) in state_dict: "module.Prediction.attention_cell.i2h.weight", "module.Prediction.attention_cell.h2h.weight", "module.Prediction.attention_cell.h2h.bias", "module.Prediction.attention_cell.score.weight", "module.Prediction.attention_cell.rnn.weight_ih", "module.Prediction.attention_cell.rnn.weight_hh", "module.Prediction.attention_cell.rnn.bias_ih", "module.Prediction.attention_cell.rnn.bias_hh", "module.Prediction.generator.weight", "module.Prediction.generator.bias".
        Unexpected key(s) in state_dict: "module.Prediction.weight", "module.Prediction.bias".

any advice on this would be helpful

**Comment by bityigoss** [comment]
@MattHuntebrinker If your model trained with 'CTC' Prediction, then in testing stage, Prediction should be 'CTC' and make sure not 'Attn'.  Hope is helps.

**Comment by ku21fan** [comment]
I think the comment of @bityigoss would solve this issue, thanks!
