### ISSUE TITLE
test on my own dataset, AssertionError: datasets should not be an empty iterable

### ISSUE THREAD

**Issue by xiaomeng654321** [clovaai/deep-text-recognition-benchmark#201]
CUDA_VISIBLE_DEVICES=0 python test.py --eval_data /home/Documents/deeptextlmdbdata/eval --benchmark_all_eval --sensitive --Transformation None --FeatureExtraction VGG --SequenceModeling BiLSTM --Prediction CTC --saved_model ./saved_models/None-VGG-BiLSTM-CTC-Seed1111/best_accuracy.pth

I train and test on my own datasets, when I run the test command on it and meet the problem:

Traceback (most recent call last):
  File "test.py", line 274, in <module>
    test(opt)
  File "test.py", line 217, in test
    benchmark_all_eval(model, criterion, converter, opt)
  File "test.py", line 43, in benchmark_all_eval
    eval_data, eval_data_log = hierarchical_dataset(root=eval_data_path, opt=opt)
  File "/home/PycharmProjects/deep-text-recognition-benchmark/dataset.py", line 124, in hierarchical_dataset
    concatenated_dataset = ConcatDataset(dataset_list)
  File "/home/anaconda3/envs/deeptextcrnn/lib/python3.6/site-packages/torch/utils/data/dataset.py", line 188, in __init__
    assert len(datasets) > 0, 'datasets should not be an empty iterable'
AssertionError: datasets should not be an empty iterable

can you help me slove it?

**Comment by janetwise** [comment]
what's your command line for training?

**Comment by xiaomeng654321** [comment]
I'm so sorry that i made a mistake about the test folder.
the train command is similar to the test folder, the difference is that the folder
thanks a lot for you
