### ISSUE TITLE
lmdb.error: Input/output error

### ISSUE THREAD

**Issue by ducbluee** [clovaai/deep-text-recognition-benchmark#205]
I encountered an error like this, not sure if anyone had encountered it and could help me resolve it
![Screenshot from 2020-07-27 15-30-15](https://user-images.githubusercontent.com/48615021/88520889-69274900-d01e-11ea-95df-099f362671cf.png)

**Comment by ku21fan** [comment]
Hello, 

I have not seen the error message, but I think [this link](https://stackoverflow.com/q/47683601) could be helpful.

Hope it helps

Best.
