### ISSUE TITLE
vertical text recognition

### ISSUE THREAD

**Issue by mathpopo** [clovaai/deep-text-recognition-benchmark#21]
First of all, thank you so much for such a wonderful job,but i try to test some vertical text,cannot detect any character,if need some train Specifically for it or model have some defects?

**Comment by kdrl** [comment]
@mathpopo Simultaneous recognition of horizontal and vertical texts in natural scene images is another interesting research topic, which is not covered in this work. For simplicity, most recent STR methods have focused on horizontal texts, and this work also follows the scheme; leaving the problem as a future work (see Section 4.5).

Using this implementation, you may train your own model on vertical texts. However, horizontal and vertical texts have different characteristics. Therefore, it can be harder to get a good model that achieves high performance on both.

**Comment by kdrl** [comment]
@mathpopo Simultaneous recognition of horizontal and vertical texts in natural scene images is another interesting research topic, which is not covered in this work. For simplicity, most recent STR methods have focused on horizontal texts, and this work also follows the scheme; leaving the problem as a future work (see Section 4.5).

Using this framework, you may train your own model on vertical texts. However, horizontal and vertical texts have different characteristics. Therefore, it can be harder to get a good model that achieves high performance on both.

**Comment by ku21fan** [comment]
@mathpopo if your model was not trained with vertical texts, the model usually cannot detect any character on vertical texts.
Thus, to recognize vertical texts, you should generate/collect some vertical texts and train with them.
Best
