### ISSUE TITLE
different image width between training and test

### ISSUE THREAD

**Issue by kingwpf** [clovaai/deep-text-recognition-benchmark#222]
Hey,
 My training width is 320 and test width is 340, which will cause mismatch issue, did this model support doing inference on different width from 320？

Traceback (most recent call last):
  File "test.py", line 286, in <module>
    test(opt)
  File "test.py", line 212, in test
    model.load_state_dict(torch.load(opt.saved_model, map_location=device), strict=False)
  File "/home/anaconda3/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 839, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DataParallel:
        size mismatch for module.Transformation.GridGenerator.P_hat: copying a param with shape torch.Size([10240, 23]) from checkpoint, the shape in current model is torch.Size([10880, 23]).

**Comment by kingwpf** [comment]
I did some debug, I found "model = torch.nn.DataParallel(model).to(device)" cause this error

**Comment by bupt-yfh** [comment]
I have the same question

**Comment by kingwpf** [comment]
> I have the same question

width should be fixed when you use tps moudle.
