### ISSUE TITLE
TPS output visualization

### ISSUE THREAD

**Issue by kingwpf** [clovaai/deep-text-recognition-benchmark#224]
Thank you for your great job, do you have any suggestion about visualizing the output of tps_stn module?

**Comment by ChangWinnie** [comment]
@kingwpf I successfully visuaize it , I follow[ this website ](https://www.cnblogs.com/sdu20112013/p/11983437.html)to transform input[1] ( type tensor) to pillow type and show it.
But the result is not good , does anyone know how to improve it?
![Screenshot from 2020-09-19 22-06-40](https://user-images.githubusercontent.com/55385048/93669219-24230e80-fac5-11ea-8b6f-0ae6249feff6.png)

**Comment by kingwpf** [comment]
> @kingwpf I successfully visuaize it , I follow[ this website ](https://www.cnblogs.com/sdu20112013/p/11983437.html)to transform input[1] ( type tensor) to pillow type and show it.
> But the result is not good , does anyone know how to improve it?
> ![Screenshot from 2020-09-19 22-06-40](https://user-images.githubusercontent.com/55385048/93669219-24230e80-fac5-11ea-8b6f-0ae6249feff6.png)

`    model.eval()
    with torch.no_grad():
        for image_tensors, image_path_list in demo_loader:
            batch_size = image_tensors.size(0)
            image = image_tensors.to(device)
            # For max length prediction
            preds = model.module.Transformation(image)
            preds = preds.mul_(0.5).add_(0.5).cpu()
            image = image.mul_(0.5).add_(0.5).cpu()
            for i in range(batch_size):
                original_image = image[i]
                transformed_image = preds[i]
                original_image = transforms.ToPILImage()(original_image)
                transformed_image = transforms.ToPILImage()(transformed_image)
                original_image = np.array(original_image)
                transformed_image= np.array(transformed_image)
                cv2.imshow('original', original_image)
                cv2.imshow('transformed', transformed_image)
                cv2.waitKey()`
