### ISSUE TITLE
 I can't proceed to the second training

### ISSUE THREAD

**Issue by ryugonomura** [clovaai/deep-text-recognition-benchmark#237]
I executed training as follows:

`python train.py --train_data data_lmdb_release/training --valid_data data_lmdb_release/validation --select_data MJ-ST --batch_ratio 0.5-0.5 --Transformation TPS --FeatureExtraction ResNet --SequenceModeling BiLSTM --Prediction Attn`

The first time was executed as shown below, but the step cannot proceed to 2/300000.
Please tell me the cause?

------------ Options -------------
exp_name: TPS-ResNet-BiLSTM-Attn-Seed1111
train_data: data_lmdb_release/training
valid_data: data_lmdb_release/validation
manualSeed: 1111
workers: 4
batch_size: 192
num_iter: 300000
valInterval: 2000
saved_model:
FT: False
adam: False
lr: 1
beta1: 0.9
rho: 0.95
eps: 1e-08
grad_clip: 5
baiduCTC: False
select_data: ['MJ', 'ST']
batch_ratio: ['0.5', '0.5']
total_data_usage_ratio: 1.0
batch_max_length: 25
imgH: 32
imgW: 100
rgb: False
character: 0123456789abcdefghijklmnopqrstuvwxyz
sensitive: False
PAD: False
data_filtering_off: False
Transformation: TPS
FeatureExtraction: ResNet
SequenceModeling: BiLSTM
Prediction: Attn
num_fiducial: 20
input_channel: 1
output_channel: 512
hidden_size: 256
num_gpu: 1
num_class: 38
---------------------------------------

[1/300000] Train loss: 3.63514, Valid loss: 3.57144, Elapsed_time: 1.75337
Current_accuracy : 0.000, Current_norm_ED  : 0.03
Best_accuracy    : 0.000, Best_norm_ED     : 0.03
--------------------------------------------------------------------------------
Ground Truth              | Prediction                | Confidence Score & T/F
--------------------------------------------------------------------------------
on                        | iinnnnnnnnnninnninnninnni | 0.0000  False
kishtwar                  | innnnnnnnnnnnnnnnnnnnnnnn | 0.0000  False
crocs                     | aannnnnnnnnnnnnnnnnnnnnnn | 0.0000  False
down                      | innnnnnnnnnnnooioioiinnnn | 0.0000  False
block                     | aaaaaaaaaaaaaaaaaaaaaaaaa | 0.0000  False
--------------------------------------------------------------------------------

**Comment by jusim** [comment]
Console output is printed each 2000 iterations (when validating). You can either change that with the `--valInterval` option or you just have to wait because it takes a while depending on the setup you use.
