### ISSUE TITLE
using this model for a scene with multiple lines of text

### ISSUE THREAD

**Issue by MattHuntebrinker** [clovaai/deep-text-recognition-benchmark#24]
Once this model is trained, when feeding an image through demo.py I can only get a word as the output as best. How can I change this code / what am I doing wrong if I want to use this to recognize images with a bunch of words on it.

**Comment by ku21fan** [comment]
Hello, 

In general, the scene text recognition task predicts one word for one image, as shown [here](https://github.com/clovaai/deep-text-recognition-benchmark#prediction-results).

Does 'images with a bunch of words on it' indicates scene image which has many text regions? like this image?
![img_16](https://user-images.githubusercontent.com/7953971/61023283-43fc7400-a3e4-11e9-884a-15f795090f50.jpg)

If that case, in my opinion, you should use scene text detection to crop each text in the scene image, and then use this code to recognize each cropped text image.

Best

**Comment by Crescentz** [comment]
can it recoginize word or sentence
