### ISSUE TITLE
Accuracy stuck on 0.000

### ISSUE THREAD

**Issue by SaeedArisha** [clovaai/deep-text-recognition-benchmark#241]
Hello, I'm training the model using my custom dataset, the training has around 1800 images, each image has multiline text. The accuracy after even 15000 iterations is not changing.
The text is English. Can someone please guide me

**Comment by pchoang96** [comment]
Did you find the solution ? Can you show it to me please. I'm in the same situation here.

**Comment by SaeedArisha** [comment]
@pchoang96 Hey, my accuracy was not increasing because the images had multi-word and multiline text, however, the model works with images that have a single word. So, change your dataset into one word per image, and then hopefully the accuracy will start improving

**Comment by altansnl** [comment]
it is possible to train multi-word models. in the allowed characters, you have to provide the "space" character as well! then it won't filter out the labels that are multi-word.

then you will start seeing in your predictions (logs while training) that you are able to predict multi-word images. 

@pchoang96 @SaeedArisha
