### ISSUE TITLE
Performance ONNX slower than Pytorch on CPU

### ISSUE THREAD

**Issue by asmitakhaneja** [clovaai/deep-text-recognition-benchmark#242]
I was able to successfuly  convert the None-ResNet-BiLSTM-CTC.pth model to ONNX format. But the performance for Onnx model is much slower than Pytorch model.
Can anyone suggest the solution this issue?

**Comment by hoozh** [comment]
@asmitakhaneja can you share how to convert pth to onnx

**Comment by kishcs** [comment]
I want to convert TRBA pth model to onnx or TensorRT. Any guide/code will be helpful.
I am not able to form the `input` for the conversion.
