### ISSUE TITLE
my custom model cannot detect some special character classes " - " (hyphen) or "." (point) 

### ISSUE THREAD

**Issue by hungtooc** [clovaai/deep-text-recognition-benchmark#255]
i set 
```character = '0123456789aáàạãảăắằẳẵặâấầẩẫậbcdđeéèẻẹểẽêếềểễệfghiíìỉĩịjklmnoóòỏõọôốồổỗộơớờởỡợpqrstuúùủũụưứừửũữựvwxyýỳỷỹỵzAÁÀẢÃẠĂẮẰẲẴẶÂẤẦẨẪẬBCDĐEÉÈẺẼẸÊẾỀỂỄỆFGHIÍÌỈĨỊJKLMNOÓÒỎÕỌÔỐỒỔỖỘƠỚỜỞỠỢPQRSTUÚÙỦŨỤƯỨỪỬỮỰVXYÝỲỶỸỴZW\/.-:' ```
and my label test/train .txt  has " - " and "." label too. but my trained model nerver appear " - " or "." 
why? thank you.

**Comment by renzhamin** [comment]
I'm having the same problem. Hyphen is not appearing.
Its also not showing when the Ground Truth is shown in a checkpoint even though in my dataset every entry has a '-' in it
Did you solve the problem ?

**Comment by renzhamin** [comment]
> I'm having the same problem. Hyphen is not appearing. Its also not showing when the Ground Truth is shown in a checkpoint even though in my dataset every entry has a '-' in it Did you solve the problem ?

Commenting out these [lines](https://github.com/clovaai/deep-text-recognition-benchmark/blob/d38c3cbfdb0c3db952d1cf866db9c6473ffc5f04/dataset.py#L213,L214) solves it
