### ISSUE TITLE
How to change feature extractor ?

### ISSUE THREAD

**Issue by yakhyo** [clovaai/deep-text-recognition-benchmark#259]
Firstly, thanks for sharing this good work. I have some questions to ask. I would be thankful if you could find a time to answer.
My questions are following:
- What was the benifit of changing the **ResNet** output to `width_heght = 26x1 and 25x1 `
- Should I modify the output of another feature extractor network to `26x1 or 25x1`?
- Can I use EfficientNet for to get better results. I mean , what do you think which part of this network need to be changed?

**Comment by TripurAR** [comment]
@yakhyo Are you able to implement using EfficientNet?

**Comment by yakhyo** [comment]
@TripurAR , nope I did not implement it.
