### ISSUE TITLE
Difference in performance between online demo website and the offline code

### ISSUE THREAD

**Issue by AyushP123** [clovaai/deep-text-recognition-benchmark#26]
Hi,
        I have been trying to run the code on these two images:

![new_img_0](https://user-images.githubusercontent.com/9451641/60959339-a5114280-a325-11e9-8ed0-f4ef9cbb4b5e.png)

![new_img_2](https://user-images.githubusercontent.com/9451641/60959373-b1959b00-a325-11e9-89c4-82ab5721d8d5.png)

I get correct results on the demo website https://demo.ocr.clova.ai/,
This is the result I get through the offline code:
First Image: he11505973
Second Image: hijo86

**Comment by ku21fan** [comment]
Hello, 

This repository shares the traditional modules that are widely used in STR tasks and provide an STR model in the paper.
Traditional STR models in the STR research are usually only trained with alphanumeric characters, thus cannot recognize special character such as '#', ':' 
That is the difference from the online demo.

Best

**Comment by QuickLearner171998** [comment]
> Hello,
> 
> This repository shares the traditional modules that are widely used in STR tasks and provide an STR model in the paper.
> Traditional STR models in the STR research are usually only trained with alphanumeric characters, thus cannot recognize special character such as '#', ':'
> That is the difference from the online demo.
> 
> Best

I ran demo.py with the case sensitive model and # , : were correctly detected.

**Comment by marcoromelli** [comment]
I did some tests and I guess there is some other difference besides the character set. The online demo seems to be a lot more accurate.
Maybe different model hyper-parameters? Or different training dataset?

**Comment by ku21fan** [comment]
@marcoromelli 
Hello, yes of course. The bigger model, more training dataset for English, Japanese, and Korean, and some additional features which improve the performance on JPN/KOR were used for the web demo :)

**Comment by marcoromelli** [comment]
Thanks for the answer @ku21fan.
Out of curiosity, is the extra data public or proprietary of clovaai?

**Comment by ku21fan** [comment]
@marcoromelli 
Most of extra data is proprietary of clovaai.
