### ISSUE TITLE
imgH, imgW, rgb params

### ISSUE THREAD

**Issue by ilyak93** [clovaai/deep-text-recognition-benchmark#269]
Hi, a question for anyone who used the model using the instructions, I've succeeded to run it, but I wonder what are those parameters and should I change them ?
In the instructions there is nothing about changing them, just noticed as my image sizes are different from the default,
which are set in the arguments default setting.
Thank you for your answer, 
respectfully, Ilya.

**Comment by lilluv** [comment]
its used to load data. i think you cant change rgb params if u use pretrained weight and u can change imgH and imgW params .
