### ISSUE TITLE
Access to other models?

### ISSUE THREAD

**Issue by QuickLearner171998** [clovaai/deep-text-recognition-benchmark#27]
Hi, can you provide other models for ex. the one with CTC instead of attn.

**Comment by ku21fan** [comment]
OK, it takes about 2days.

**Comment by ku21fan** [comment]
Hello, 

I just uploaded 2 CTC models (1,2) at [here](https://drive.google.com/drive/folders/15WPsuPJDCzhp2SvYZLRj8mAlT3zmoAMW)
1. None_VGG_None_CTC
2. None_VGG_BiLSTM_CTC 
and we are training 2 models (3,4) as well.
3. None_ResNet_None_CTC
4. TPS_ResNet_BiLSTM_CTC
3,4 will be also uploaded soon.

Best

**Comment by ku21fan** [comment]
I just uploaded 3,4 models :)
3. None_ResNet_None_CTC
4. TPS_ResNet_BiLSTM_CTC
