### ISSUE TITLE
Case Sensitive Option Not Working while running demo.py

### ISSUE THREAD

**Issue by abdur75648** [clovaai/deep-text-recognition-benchmark#275]
I tried both the commands 
`py demo.py --Transformation TPS --FeatureExtraction ResNet --SequenceModeling BiLSTM --Prediction Attn --image_folder demo_image/ --saved_model TPS-ResNet-BiLSTM-Attn-case-sensitive.pth` & `py demo.py --sensitive --Transformation TPS --FeatureExtraction ResNet --SequenceModeling BiLSTM --Prediction Attn --image_folder demo_image/ --saved_model TPS-ResNet-BiLSTM-Attn.pth`
```
but getting this Error:
> RuntimeError: Error(s) in loading state_dict for DataParallel:
>         size mismatch for module.Prediction.attention_cell.rnn.weight_ih: copying a param with shape torch.Size([1024, 352]) from checkpoint, the shape in current model is torch.Size([1024, 294]).
>         size mismatch for module.Prediction.generator.weight: copying a param with shape torch.Size([96, 256]) from checkpoint, the shape in current model is torch.Size([38, 256]).
>         size mismatch for module.Prediction.generator.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([38]).

Please tell if I'm mistakening

**Comment by lezwon** [comment]
Facing the same issue.

**Comment by elvinyhlee** [comment]
try this pretrained model instead ` TPS-ResNet-BiLSTM-Attn-case-sensitive.pth`

**Comment by rafisoeharto** [comment]
try TPS-ResNet-BiLSTM-Attn-case-sensitive.pth , with `--sensitive`

**Comment by ezzaimsoufiane** [comment]
Facing the same issue, even with `-- sensitive` option

**Comment by MuntahaShams** [comment]
@ezzaimsoufiane have u solved ur issue?

**Comment by abdur75648** [comment]
Saved model weights are wrong, please try train one yourself from scratch
