### ISSUE TITLE
No bn layers in CRNN ?

### ISSUE THREAD

**Issue by jianxiangm** [clovaai/deep-text-recognition-benchmark#28]
Hi, I found the CRNN network implement in the project is different from the original one, which has a bn layer following each conv2d layer. I wonder why you remove them. Thanks.

**Comment by ku21fan** [comment]
Hello, 

The below table shows the architecture of CRNN, original one **only has two BN, not each** 
![스크린샷_071119_014051_PM](https://user-images.githubusercontent.com/7953971/61022595-81133700-a3e1-11e9-9fc6-eb66f2edcff8.jpg)

Best
