### ISSUE TITLE
Error While Training Custom Dataset

### ISSUE THREAD

**Issue by ctcheune** [clovaai/deep-text-recognition-benchmark#299]
I ran the ```create_lmdb_dataset.py ``` script and successfully created the data.mbd and lock.mbd and put them into the ```data_lmbd_release/training``` directory. But when I ran the ```train.py``` script, I got the following error:

AssertionError: datasets should not be an empty ot be an empty iterable'  # type: ignor
iterable

Am I supposed to split my data beforehand into evaluation, training and validation sets and then run the ```create_lmdb_dataset.py ``` script on each of them?

Thanks for your help!

**Comment by ctcheune** [comment]
Solved!

**Comment by lyc728** [comment]
> Solved!
hello how did you sovle it ?
