### ISSUE TITLE
Whether you will give the best models?

### ISSUE THREAD

**Issue by xiaoyubing** [clovaai/deep-text-recognition-benchmark#3]
Whether you will give the best models?

**Comment by ku21fan** [comment]
Yes, we will give the best models, soon.
Please wait for 1 or 2days.

**Comment by ku21fan** [comment]
We just uploaded a pre-trained model and updated README.md.
You can download the pre-trained model from [here](https://drive.google.com/drive/folders/15WPsuPJDCzhp2SvYZLRj8mAlT3zmoAMW).

Best,
