### ISSUE TITLE
Does ctc requires a blank character ?

### ISSUE THREAD

**Issue by thomasryck** [clovaai/deep-text-recognition-benchmark#31]
Does in the alphabet I have to add a blank character to have ctc working properly ? Or can I use the same alphabet as the same one foe the attention prediction?

**Comment by alwc** [comment]
Note: I'm not one of the authors

[If you look at the `CTCLabelConverter` class, you can see a blank character is added to the character dictionary.](https://github.com/clovaai/deep-text-recognition-benchmark/blob/master/utils.py#L13)

**Comment by cvchongci** [comment]
How to recognize blank between two English words?
for my current model, if I input one English sentence then the output will concatenate all the English words together. for example:
inputed image:
<img width="363" alt="36" src="https://user-images.githubusercontent.com/62248916/80300616-539c4c00-87af-11ea-93d8-1ba1b150594d.png">
recognized result:

> A------l-ll-t-h--e--r-e-c--o--g-n-i-tiio---n--a-c-cc--ur-a--c-i-e-s---o--n--t-h---e => Alltherecognitionaccuraciesonthe

So how to recognize the blank between two English words?

Thank you so much.
