### ISSUE TITLE
Unable to train model.

### ISSUE THREAD

**Issue by jingjie181** [clovaai/deep-text-recognition-benchmark#313]
Hi, I  am trying to train the model on Thai characters but I am facing this error: 

![image](https://user-images.githubusercontent.com/90379470/139564551-4f6de0e1-d887-4c9b-94ed-1b6708397d71.png)

My gt file follows the format `{imagepath}\t{label}\n`. In another comment, it was mentioned that this error arises when the lmdb dataset is created wrongly. Is there anyway to check if the lmdb dataset is created properly?

I have also changed the character list as follows: 

![image](https://user-images.githubusercontent.com/90379470/139395388-a4a9e7f0-a466-4989-97dc-057c3f668d4d.png)

 and also updated `--select_data` and `--batch_ratio` as follows: 

![image](https://user-images.githubusercontent.com/90379470/139564581-73df9958-090f-41ea-8f9a-83d152c4947f.png)
  
but I am still facing the same error when I try to train using the command 
``` train.py --train_data C:/Users/joman/Desktop/easyocr/single_line/data_train/result/ --valid_data C:/Users/joman/Desktop/easyocr/single_line/data_valid/result/ --Transformation None --FeatureExtraction VGG --SequenceModeling BiLSTM --Prediction CTC --data_filtering_off ```

 

Is there anything I am missing out?

**Comment by emigomez** [comment]
Hi @jingjie181 
Did you find the solution?
I'm having similar error

**Comment by AKKHTN2131999** [comment]
I think **--select_data** should be passed as **test** instead of the full path. And you should put all the LMDB data for training into a directory, then pass the **train_data** argument as the path to this directory.

I think you're done. But I also wrote it in the hope that it might help someone.
