### ISSUE TITLE
Can the model be used for Chinese STR case retrained?

### ISSUE THREAD

**Issue by iPrayerr** [clovaai/deep-text-recognition-benchmark#33]
Hey, I just found that you've done a really fantastic job.
Seems like it works on English, Korean & Japanese STR.
So...if I retrained the model with Chinese STR datasets(like RCTW, etc.), can it still work?
I don't know if you've tried such work. It'll be great if I could get more suggestions.

**Comment by ku21fan** [comment]
@iPrayerr 
Hello, 
I have not tried to re-train with different language/character sets (such as pretrained English model to Chinese model) yet.
I have usually trained from scratch and it worked with Chinese dataset.
Thus, I can't sure but I think re-training the model with Chinese STR datasets would also work.

How about change and retrain character set and last feed-forward layer which predicts characters?

Best

**Comment by Crescentz** [comment]
Have you solved the problem of training Chinese? How to train
