### ISSUE TITLE
Results different with online Demo

### ISSUE THREAD

**Issue by crazysal** [clovaai/deep-text-recognition-benchmark#35]
Hi, 
Thanks a lot for this great effort. 

However in, using pretrained model provided and outputs inferred on the demo site (https://demo.ocr.clova.ai)  the results vary greatly. 

The online demo is able to recognize the text but the local inference using TPS-ResNet-BiLSTM-Attn.pth provided fails miserably. 

Can you please elaborate about extra steps taken on demo site model ? Or any other extra pre-processing/post processing steps involved. 

[Testimages](https://drive.google.com/file/d/1tPGwluZyTvXmWVigI4AtP7_e42ul36Lf/view?usp=sharing)

**Comment by solitaire2015** [comment]
Same question as https://github.com/clovaai/deep-text-recognition-benchmark/issues/26
