### ISSUE TITLE
Poor prediction for Indic languages despite decent training accuracies.

### ISSUE THREAD

**Issue by ceyxasm** [clovaai/deep-text-recognition-benchmark#358]
Hello, I have used the model to train on my own dataset. It had 88k handwritten words in Bengali. 
![image](https://user-images.githubusercontent.com/73417805/191466150-c6d32e27-2901-4af7-878f-887c7616dc20.png)

Despite pretty decent training results, the prediction is straight up bad. 
It just predicts the same character over and over again for all the inputs.
![image](https://user-images.githubusercontent.com/73417805/191466488-29ed5951-1196-458c-86d0-34d16b7a4f1d.png)

Does anyone know what can be the issue, because previously I tried a very different model for same and that too gave same single character prediction for all the images.

**Comment by ceyxasm** [comment]
So I found what the issue was;
While training feature extractor used was VGG but ResNet during prediction; so I had to correct that
Next, instead of using attention; CTC gave better results
character filtering was also turned off for better results

**Comment by MohieEldinMuhammad** [comment]
https://github.com/JaidedAI/EasyOCR/issues/892 

Can you help me with this issue, I'm also facing an issue after generating the .pth model --> the results are very bad when tying to predict although the training was very good

**Comment by akashlp27** [comment]
Hey @ceyxasm , can u give some info regarding the dataset used for handwritten training for bengali....? will help a lot thanks

**Comment by ceyxasm** [comment]
> Hey @ceyxasm , can u give some info regarding the dataset used for handwritten training for bengali....? will help a lot thanks

**Comment by ceyxasm** [comment]
> Hey @ceyxasm , can u give some info regarding the dataset used for handwritten training for bengali....? will help a lot thanks

I used ICFHR dataset. 
You can find it here: http://cvit.iiit.ac.in/ihtr2022/dataset.html
