### ISSUE TITLE
Does the model support variable length recognition？I train the model using Chinese STR Datasets，but have a bad accuracy

### ISSUE THREAD

**Issue by AnddyWang** [clovaai/deep-text-recognition-benchmark#37]
Does the model support variable length recognition，I train the model using Chinese STR Datasets，but have a bad accuracy
I use TPS-ResNet、VGG-BiLSTM-Attn。
What should I do to have a normal accuracy？

**Comment by ku21fan** [comment]
@AnddyWang 
Hello, 
Yes, the model support variable-length til 25 characters as default, and you can change it.
see https://github.com/clovaai/deep-text-recognition-benchmark/blob/master/train.py#L221

I recommend to 
1. check your training dataset whether it is enough to learn Chinese character sets. Many and various type of training dataset would improve accuracy.
2. change max length (if you think the length is the problem)

Best.

**Comment by AnddyWang** [comment]
> @AnddyWang
> Hello,
> Yes, the model support variable-length til 25 characters as default, and you can change it.
> see https://github.com/clovaai/deep-text-recognition-benchmark/blob/master/train.py#L221
> 
> I recommend
> 
> 1. check your training dataset whether it is enough to learn Chinese character sets. Many and various type of training dataset would improve accuracy.
> 2. change max length (if you think the length is the problem)
> 
> Best.

Thanks,  I train the model using 32X256,  then  set batch_max_length=64(test train), anything else?

**Comment by AnddyWang** [comment]
@ku21fan The training dataset is enough to train。
I train the model using 32X256, then set batch_max_length=64(test and train)， anything else to modify?

**Comment by ku21fan** [comment]
@AnddyWang 
Nope, try with them.
Hope it works!

**Comment by xxxxxxxiao** [comment]
Hi! could you tell me if you got improvement on chinese datasets? did it work well? thx.
