### ISSUE TITLE
The text shape when using Attention 

### ISSUE THREAD

**Issue by SakuraRiven** [clovaai/deep-text-recognition-benchmark#38]
Hi, thank you for sharing such great work! I am a novice and found sth i cannot understand:

The ```AttnLabelConverter``` encodes the labels into ```text, length```. The ```text``` has shape ```[batch_size, max_length+2]``` where '2' means [go] and [stop].

When the ```text``` pass into ```Attention.forward()```, however, the notes said ```text : the text-index of each image. [batch_size x (max_length+1)]. +1 for [GO] token. text[:, 0] = [GO].```

Are these two ```text``` the same object? If so, why the shape is different? 
Thanks for you help!

**Comment by ku21fan** [comment]
@SakuraRiven 
Hello, 
Yes, they are the same object.
I just fix it, with below code :)
https://github.com/clovaai/deep-text-recognition-benchmark/blob/a239f46df35b85f5c39af9f74152bd45b1301639/train.py#L138

Before fixed it, even if the model get input 'text' whose shape is [batch_size, max_length+2], the attention decoder loops [batch_size, max_length+1] as below.
https://github.com/clovaai/deep-text-recognition-benchmark/blob/a239f46df35b85f5c39af9f74152bd45b1301639/modules/prediction.py#L30
Thus, the result would be the same before :)

best.
