### ISSUE TITLE
How to make custom dataset random?

### ISSUE THREAD

**Issue by Hye0nJ** [clovaai/deep-text-recognition-benchmark#383]
Hi! Thank you for great work!
I'm making a custom dataset with own dictionary.
But the results are same. which parameter can i use it?

here's example.
I always get same datasets like apple and orange.
I want to get datasets randomly

`trdg -c 2 -i own_dictionary.txt`

own_dictionary.txt 
1. apple
2. orange
3. pineapple

**Comment by creati0nix** [comment]
use chatgpt or synthtiger
