### ISSUE TITLE
create_dataset

### ISSUE THREAD

**Issue by CXY573** [clovaai/deep-text-recognition-benchmark#4]
Hello,I can not open the dataset link,so can you provide the create_dataset.py that i can create my own training dataset?

**Comment by ku21fan** [comment]
Yes, we provide create_lmdb_dataset.py
https://github.com/clovaai/deep-text-recognition-benchmark/blob/master/create_lmdb_dataset.py

How to use: https://github.com/clovaai/deep-text-recognition-benchmark#when-you-need-to-create-lmdb-dataset

Best.

**Comment by CXY573** [comment]
OK,I will read the code.So have you reached the accurary as the paper show?

**Comment by ku21fan** [comment]
Yes, this code is the official version of [this paper](https://arxiv.org/abs/1904.01906).
However, this code is slightly different from the paper version. 
(ex. some parts of the code are modified for the readability, and some additional features are added.)
Thus, the results also could be slightly different from the results of the paper.

**Comment by CXY573** [comment]
Wow,I just realized that you were the author. Thank you very much for providing code.
