### ISSUE TITLE
Train --sensitive mode with the  MJSynth + ST_spe

### ISSUE THREAD

**Issue by mahendra047** [clovaai/deep-text-recognition-benchmark#40]
Hi,
Great work from you, and thanks for the sharing.
I trained the model on --sensitive mode with the  MJSynth + ST_spe . here are the training accuracy and loss:
[79000/300000] Loss: 0.09761 elapsed_time: 103154.51228
FOR,                , gt: FOR                 ,   False
Mo-vediplon         , gt: MOVCD1PLO1          ,   False
REBATE              , gt: REBATE              ,   True
WALK                , gt: WALK                ,   True
NISSAN-SBI          , gt: NISSANSBI           ,   False
[79000/300000] valid loss: 2.17037 accuracy: 58.939, norm_ED: 2006.77
best_accuracy: 60.812, best_norm_ED: 1922.32

**model gives constant accuracy from this iteration **

[47500/300000] valid loss: 2.29950 accuracy: 56.822, norm_ED: 2124.85
best_accuracy: 60.812, best_norm_ED: 1922.32
[48000/300000] Loss: 0.11939 elapsed_time: 62696.96234
proudly             , gt: proudly             ,   True
LOVE                , gt: LOVE                ,   True
SAXONS              , gt: SAXONS              ,   True
TESCO               , gt: TESCO               ,   True

------------ Options -------------
experiment_name: TPS-ResNet-BiLSTM-Attn-Seed1111
train_data: data_lmdb_release/training
valid_data: data_lmdb_release/validation
manualSeed: 1111
workers: 4
batch_size: 192
num_iter: 300000
valInterval: 500
continue_model:
adam: False
lr: 1
beta1: 0.9
rho: 0.95
eps: 1e-08
grad_clip: 5
select_data: ['MJ', 'ST_spe']
batch_ratio: ['0.5', '0.5']
total_data_usage_ratio: 1.0
batch_max_length: 25
imgH: 32
imgW: 100
rgb: False
character: 0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~"
sensitive: True
PAD: False
data_filtering_off: False
Transformation: TPS
FeatureExtraction: ResNet
SequenceModeling: BiLSTM
Prediction: Attn
num_fiducial: 20
input_channel: 1
output_channel: 512
hidden_size: 256
num_gpu: 1
num_class: 96
---------------------------------------
should i stop training ... 
What should I do to have a good accuracy？

**Comment by solitaire2015** [comment]
@mahendra047 Here is my training log, I made a little bit change (https://github.com/clovaai/deep-text-recognition-benchmark/issues/7#issuecomment-513057240).
I think your model isn't converged yet.

[48000/300000] Loss: 0.12339 elapsed_time: 18899.38025
BEECHES             , gt: BEECHES             ,   True
JEM                 , gt: JEM                 ,   True
HENG                , gt: HENG                ,   True
Endless             , gt: ENDLESS             ,   False
look                , gt: lock                ,   False
[48000/300000] valid loss: 1.94635 accuracy: 59.940, norm_ED: 1931.75
best_accuracy: 61.456, best_norm_ED: 1792.03

[100000/300000] Loss: 0.09535 elapsed_time: 47135.06759
STYLE               , gt: STYLE               ,   True
2015                , gt: 2015                ,   True
SANI                , gt: SAN                 ,   False
SPORTS              , gt: SPORTS              ,   True
books               , gt: books               ,   True
[100000/300000] valid loss: 1.95312 accuracy: 62.757, norm_ED: 1737.70
best_accuracy: 63.787, best_norm_ED: 1720.06

[150000/300000] Loss: 0.08197 elapsed_time: 77372.36088
CREATE              , gt: CREATE              ,   True
250                 , gt: 250                 ,   True
CONDERES            , gt: Alpha               ,   False
2                   , gt: 2                   ,   True
DAWN                , gt: DAWN                ,   True
[150000/300000] valid loss: 1.96480 accuracy: 64.416, norm_ED: 1686.38
best_accuracy: 64.416, best_norm_ED: 1686.38

[200000/300000] Loss: 0.07478 elapsed_time: 101645.12309
Trichokare          , gt: TRICHOKARE          ,   False
Neot                , gt: NESCAFE             ,   False
STORY               , gt: STORY               ,   True
Restaurant          , gt: RESTAURANT          ,   False
ASTRON              , gt: ASTRON              ,   True
[200000/300000] valid loss: 1.94974 accuracy: 65.174, norm_ED: 1683.50
best_accuracy: 65.389, best_norm_ED: 1663.67

[250000/300000] Loss: 0.06913 elapsed_time: 125046.85118
FREEDOM             , gt: FREEDOM             ,   True
Apica               , gt: Alice               ,   False
multimedia          , gt: muLtImeDIa          ,   False
Registered          , gt: Registered          ,   True
the                 , gt: THE                 ,   False
[250000/300000] valid loss: 1.99279 accuracy: 64.917, norm_ED: 1674.51
best_accuracy: 65.575, best_norm_ED: 1652.86

[280000/300000] Loss: 0.06764 elapsed_time: 139501.60188
ARCADE              , gt: ARCADE              ,   True
WAY                 , gt: WAY                 ,   True
SAL                 , gt: SAL                 ,   True
washington          , gt: WASHINGTON          ,   False
raised              , gt: raised              ,   True
[280000/300000] valid loss: 2.01600 accuracy: 65.203, norm_ED: 1728.07
best_accuracy: 66.390, best_norm_ED: 1609.72

**Comment by ku21fan** [comment]
@mahendra047 
Hello,
The best accuracy means the best valid accuracy until now.
And the current accuracy is this, and it is changing in your logs.
[79000/300000] valid loss: 2.17037 **accuracy: 58.939 (this is current accuracy)**, norm_ED: 2006.77
[47500/300000] valid loss: 2.29950 **accuracy: 56.822 (this is current accuracy)**, norm_ED: 2124.85

as @solitaire2015 said, your model isn't converged yet. (Thank you for answering!)

(p.s.) If you use `--sensitive` mode, the valid accuracy on our validation data is lower than the insensitive mode. 
The reason is described here https://github.com/clovaai/deep-text-recognition-benchmark/issues/29#issuecomment-511273459 

Best
