### ISSUE TITLE
I encountered a bug when executing the following command in the deep-text-recognition-benchmark repository

### ISSUE THREAD

**Issue by Floracq64** [clovaai/deep-text-recognition-benchmark#408]
During the execution, the following output and traceback error were observed:

```
Filtering the images containing characters which are not in opt.character
Filtering the images whose label is longer than opt.batch_max_length

dataset_root: ../
opt.select_data: ['MJ', 'ST']
opt.batch_ratio: ['0.5', '0.5']

Attempting to open LMDB at ../
dataset_root:    ../     dataset: MJ
True
sub-directory:  /MJ      num samples: 159
num total samples of MJ: 159 x 1.0 (total_data_usage_ratio) = 159
num samples of MJ per batch: 192 x 0.5 (batch_ratio) = 96

Attempting to open LMDB at ../
dataset_root:    ../     dataset: ST
True
Traceback (most recent call last):
  File "A:\test\deep-text-recognition-benchmark\train.py", line 317, in <module>
    train(opt)
  File "A:\test\deep-text-recognition-benchmark\train.py", line 31, in train
    train_dataset = Batch_Balanced_Dataset(opt)
  File "A:\test\deep-text-recognition-benchmark\dataset.py", line 42, in __init__
    _dataset, _dataset_log = hierarchical_dataset(root=opt.train_data, opt=opt, select_data=[selected_d])
  File "A:\test\deep-text-recognition-benchmark\dataset.py", line 119, in hierarchical_dataset
    dataset = LmdbDataset(dirpath, opt)
  File "A:\test\deep-text-recognition-benchmark\dataset.py", line 137, in __init__
    self.env = lmdb.open(root, max_readers=32, readonly=True, lock=False, readahead=False, meminit=False)
lmdb.Error: ..//deep-text-recognition-benchmark\saved_models\TPS-ResNet-BiLSTM-Attn-Seed1111: No such file or directory
```
I have already changed the paths several times without any success. The directory is correctly created, but the error persists. I would appreciate any assistance to resolve this issue.

Steps to Reproduce:

1. Navigate to the deep-text-recognition-benchmark directory.
2. Execute the command mentioned above.
3. Observe the traceback error.
Environment:

- OS: (e.g., Windows 10)
- Python Version: (e.g., 3.8)
d
![Capture d'écran 2023-09-23 221039](https://github.com/clovaai/deep-text-recognition-benchmark/assets/101367300/04493fc7-2755-4993-9413-dddcedadc2c2)
![Capture d'écran 2023-09-23 221552](https://github.com/clovaai/deep-text-recognition-benchmark/assets/101367300/376a9981-5618-487d-8470-d2a2a4a49443)

eep-text-recognition-benchmark version: (e.g., latest from the repository as of date)
Additional Context:

I have tried different path configurations, ensuring that the directories exist and are accessible.
The saved model path provided in the command is ./saved_models/custom_example.pth.
It seems like the program is attempting to access a different path (TPS-ResNet-BiLSTM-Attn-Seed1111) which does not exist, as indicated in the error message.

**Comment by Seoung-wook** [comment]
The path seems to be wrong.
your path: ..//deep-text-recognition-benchmark\saved_models\TPS-ResNet-BiLSTM-Attn-Seed1111

edit .\deep-text-recognition-benchmark\saved_models\TPS-ResNet-BiLSTM-Attn-Seed1111
or .\saved_models\TPS-ResNet-BiLSTM-Attn-Seed1111
