### ISSUE TITLE
recog error using  TPS-ResNet、VGG-BiLSTM-Attn

### ISSUE THREAD

**Issue by AnddyWang** [clovaai/deep-text-recognition-benchmark#43]
The sample images
![d_autohomecar__wKgHPltYXyWAZHTbAANpvWtj5Hs964_0](https://user-images.githubusercontent.com/19400072/62103017-b965b100-b2cd-11e9-9360-45fb9e1fd8d2.jpg)  和兰豪华感，而风上的    wrong
![d_autohomecar__wKgHPltYXyWAZHTbAANpvWtj5Hs964_1](https://user-images.githubusercontent.com/19400072/62103018-b9fe4780-b2cd-11e9-9dfb-be07048af954.jpg)  内饰设局觉觉温馨范儿   wrong
![d_autohomecar__wKgHPlstHCiANf7JAAGvh7L-4DU249_1](https://user-images.githubusercontent.com/19400072/62103020-b9fe4780-b2cd-11e9-94d0-130fa13ff16f.jpg)  后扭力梁非独立悬架    correct
![d_autohomecar__wKgHPlt2pX6AQNrVAANoQlFZZXQ045_0](https://user-images.githubusercontent.com/19400072/62103021-ba96de00-b2cd-11e9-932b-0b9b9a6b907a.jpg)  变之水波落务变得更出  wrong

I train the model using 32X256, then set batch_max_length=64(test and train)，I feel something has wrong，when the character has many in the sample，the result is wrong。

The traing datasets is normal。

Thanks

**Comment by simplify23** [comment]
excuse me, how can you modify this work and run. please tell the detail and the train dataset,thanks

**Comment by AnddyWang** [comment]
> excuse me, how can you modify this work and run. please tell the detail and the train dataset,thanks

modify the size of image and the batch_max_length

**Comment by AnddyWang** [comment]
I think the code doesn't support variable predict，but I don't know how to modiy。

**Comment by AnddyWang** [comment]
I think the code doesn't support variable predict，but I don't know how to modiy。

**Comment by AnddyWang** [comment]
I think the code doesn't support variable predict，but I don't know how to modiy。
I have modify the resize image to scale based on a fixed height（32）。
Can anyone give me some sugestion？
Thanks。
@ku21fan

**Comment by ku21fan** [comment]
Hello, 
Can you upload the train_log file to check?

If you train with 32x256 image, you should test with 32x256 image (with `--imgW 256`), instead of scaling based on a fixed height（32）.

**Comment by ku21fan** [comment]
I think I found the reason! 
I forgot to give batch_max_length argument in converter.encode() function.
I just fixed it. Sorry about it.
https://github.com/clovaai/deep-text-recognition-benchmark/commit/bda81065a52a2c7612ee947bde0cece62151c61d

**Comment by AnddyWang** [comment]
> @AnddyWang I think I found the reason!
> I forgot to give batch_max_length argument in converter.encode() function.
> I just fixed it with below commit.
> [bda8106](https://github.com/clovaai/deep-text-recognition-benchmark/commit/bda81065a52a2c7612ee947bde0cece62151c61d)
> [533fdf0](https://github.com/clovaai/deep-text-recognition-benchmark/commit/533fdf01ba3bc7fe2328dd2bbb3c0e5091d5e6a7)
> 
> Sorry about it. and hope it works!

I have correct the error of encode label before traing and testing，the result is tested by the modified codes.

**Comment by AnddyWang** [comment]
> Hello,
> Can you upload the log_train.txt file and opt.txt file to check?
> 
> If you train with 32x256 image, you should test with 32x256 image (with `--imgW 256`), instead of scaling based on a fixed height（32）.

I think the test image should be scaled based on a fixed height（32）.
for example, the width of a test image is greater than 256, such as 1024, when resizing to be 256, the image will be distorted，the recognition result is wrong.

the sequence should be variable by the width, 256->64; 1024 should be 256.

How about this solution  for the test image which has a greater width than 256 and many characters ?

**Comment by ku21fan** [comment]
hmm.. 
Then... I think I need to check log_train.txt file and opt.txt file.
Can you upload or email them to me?

It always outputs < 10 characters, so something is weird..

[about Test image size]
Yes, your solution would be good and worth testing. 
However, I didn't test with that, so I can't guarantee it.
I had trained and tested with 32x192 for some long Chinese text and it still worked. (not perfectly though)

**Comment by AnddyWang** [comment]
the opt.txt  and the log_train are as follows:
[opt.txt](https://github.com/clovaai/deep-text-recognition-benchmark/files/3450688/opt.txt)
![0E6194C9-7790-43f5-80F7-42E89CAFEC67](https://user-images.githubusercontent.com/19400072/62198215-d2489200-b3b3-11e9-9519-ce09650ebe4f.png)

Thanks for your reply.

**Comment by ku21fan** [comment]
Hello, 

Sorry for the late reply.
Is your problem solved?

I checked your `opt.txt`.
I need to check whether the validation results in the training time are fine or not.
However, your valInterval is 600000, thus I could not check the validation results.

If your problem is not solved, can you test with valInterval 2000 and upload the validation results such as below image? (`log_train.txt` would contain this information)
![스크린샷_082719_054738_PM](https://user-images.githubusercontent.com/7953971/63756101-c4265c80-c8f2-11e9-842b-5879d80392ef.jpg)

Best

**Comment by AnddyWang** [comment]
![image](https://user-images.githubusercontent.com/19400072/63758935-2ed59900-c8ef-11e9-85e4-874a11b89b59.png)
This is the validation result，I use none-tps train the model，but the model does not support the variable length .

**Comment by ku21fan** [comment]
I guess that the print function below would be a problem (because it only prints 10 characters), and the model would support variable length rightly (since the accuracy is good enough?).
https://github.com/clovaai/deep-text-recognition-benchmark/blob/master/train.py#L171-L172
Try to change 
```
                    print(f'{pred:20s}, gt: {gt:20s},   {str(pred == gt)}')
                    log.write(f'{pred:20s}, gt: {gt:20s},   {str(pred == gt)}\n')
```
into
```
                    print(f'{pred}, gt: {gt},   {str(pred == gt)}')
                    log.write(f'{pred}, gt: {gt},   {str(pred == gt)}\n')
```
and then check the validation result.

**Comment by akarazniewicz** [comment]
Natrually BiLSTM and Attention embedds some language features, so model needs to be retraind for longer sequences, which are not present in SyntText. I did retrain TPS-ResNet-BiLSTM-Attn for longer text sequences for my own research and it works pretty well. Just increased imgW and batch_max_length.

**Comment by AnddyWang** [comment]
> I guess that the print function below would be a problem (because it only prints 10 characters),
> and the model would support variable length rightly (since the accuracy is good enough?).
> https://github.com/clovaai/deep-text-recognition-benchmark/blob/master/train.py#L171-L172
> Try to change
> 
> ```
>                     print(f'{pred:20s}, gt: {gt:20s},   {str(pred == gt)}')
>                     log.write(f'{pred:20s}, gt: {gt:20s},   {str(pred == gt)}\n')
> ```
> 
> into
> 
> ```
>                     print(f'{pred}, gt: {gt},   {str(pred == gt)}')
>                     log.write(f'{pred}, gt: {gt},   {str(pred == gt)}\n')
> ```
> 
> and then check the validation result.

Not work，the gt only has 10 characters which is correct。

**Comment by AnddyWang** [comment]
> Natrually BiLSTM and Attention embedds some language features, so model needs to be retraind for longer sequences, which are not present in SyntText. I did retrain TPS-ResNet-BiLSTM-Attn for longer text sequences for my own research and it works pretty well. Just increased imgW and batch_max_length.

Thanks your reply，but not the same problem。
I mean to predict images of the variable length，for example，if your model is trained by 32 x 256 ；can your model predict a image with 32X760  or  32X48 correctly ?

**Comment by ku21fan** [comment]
Hmm.. in this case, I'll close this issue. 
Because
1. This issue is about the limitation of the recognition model, rather than `recog error` of this repository.
2. This repository is not intended to cover images of variable width (too short or too long).
Thus, this repository can not handle it perfectly. 
and some points to alleviate the problem of variable width are already discussed. 
(+ I guess `--pad` option would help in some cases)

Best
