### ISSUE TITLE
probelm about attention

### ISSUE THREAD

**Issue by xiaoshuizhu202** [clovaai/deep-text-recognition-benchmark#45]
I have a question about the code with attention,the hidden state is always zeros,and in my think,it should be a encoded hidden state of batch_H with lstm , and in you code  I can't think what function the rnn_cell do?

**Comment by ku21fan** [comment]
Hello,
This line is for initial hidden value (0), this means 'not always zero'.
https://github.com/clovaai/deep-text-recognition-benchmark/blob/master/modules/prediction.py#L33

and loop attention_cell in here.
https://github.com/clovaai/deep-text-recognition-benchmark/blob/master/modules/prediction.py#L41

and LSTMCell is in the attention_cell.
https://github.com/clovaai/deep-text-recognition-benchmark/blob/master/modules/prediction.py#L67

Best.
