### ISSUE TITLE
requires_grad

### ISSUE THREAD

**Issue by soldierofhell** [clovaai/deep-text-recognition-benchmark#47]
Hi,
In train.py and test.py there's a manual loop for setting `requires_grad=True/False`. Is it really necessary? Why don't use `with torch.no_grad()` context for whole validation part? On the other hand such context is used in `test.validation()`, but just for input tensors, when it's unnecessary, because tensors by default have `requires_grad=False`.
Sorry, I don't want to be too pedantic, in the end everything works fine, but just for the clarity :)

Regards,

**Comment by ku21fan** [comment]
@soldierofhell Hello,
Nice suggestion! 
I just updated related codes.
Thank you :)
