### ISSUE TITLE
Can't training model with own lmdb dataset

### ISSUE THREAD

**Issue by thangtran480** [clovaai/deep-text-recognition-benchmark#49]
I have a problem training model with own lmdb dataset. I use _create_lmdb_dataset.py_ with 1000 sample Vietnamese to create database. When I training model, 
dataset_root: data/training
opt.select_data: ['ST']
opt.batch_ratio: ['0.5']
--------------------------------------------------------------------------------
dataset_root:    data/training	 dataset: ST
sub-directory:	/ST	 num samples: 3
num total samples of ST: 3 x 1.0 (total_data_usage_ratio) = 3
num samples of ST per batch: 192 x 0.5 (batch_ratio) = 96
--------------------------------------------------------------------------------
Total_batch_size:  96 = 96

Can you please tell me how to training own database. Thank you

**Comment by ku21fan** [comment]
Hello, 

```
sub-directory:	/ST	num samples: 3
num total samples of ST: 3 x 1.0 (total_data_usage_ratio) = 3
```
The message indicates that there are only 3 samples to train, in the path `data/training/ST`.

Check the followings
1. set `opt.character` for Vietnamese. 
By default, the character set is only alphanumeric `[a-z0-9]` and images containing characters which are not in `opt.character` are filtered. see here
https://github.com/clovaai/deep-text-recognition-benchmark/blob/master/dataset.py#L142
2. your lmdb dataset path **name** for `--train_data` and `--select_data` 

Best

**Comment by xiniang** [comment]
thanks

**Comment by thangtran480** [comment]
Thanks you for support me :)

**Comment by ThanhNhann** [comment]
@thangtran480 
I have a problem when retraining my own vietnamese dataset. Specifically, when I train, the labels of all data when covert to lmdb with the special character like â,ê,ư,ơ were disappeared
![image](https://user-images.githubusercontent.com/28915032/94996172-32951e00-05cd-11eb-9502-a868cbf56425.png)

**Comment by thangtran480** [comment]
@ThanhNhann 
Tôi nghĩ bạn nên để training đủ lâu và tách riêng bộ cho số và chữ khác nhau thì sẽ tốt hơn

**Comment by ThanhNhann** [comment]
@thangtran480  Phần xử lý nội dung tiêng việt trong code anh có điều chỉnh thêm những gì vậy anh?

**Comment by farshokat** [comment]
@thangtran480 b train model dữ liệu lớn không ạ? thời gian như thế nào ạ? tks

**Comment by thangtran480** [comment]
@farshokat
Mình tạo khoảng 100k dữ liệu được gen từ https://github.com/gungui98/SynthText. Training khoảng 50 epoch thì test thấy độ chính sác của các chữ có dấu không được tốt
