### ISSUE TITLE
fixed image size

### ISSUE THREAD

**Issue by chenjun2hao** [clovaai/deep-text-recognition-benchmark#50]
whether resize to 32×100  matter if the text image has a large width and height ratio when the image has a large width. for example, one image is 32×80, another is:32×300. is this also use _AlignCollate? looking for your replay.

**Comment by ku21fan** [comment]
Hello,

32x80 and 32x300 both use `_AlignCollate` and I guess it would matter.
However, the attention mechanism would alleviate the image ratio problem remarkably, so it would not be a big problem.
If you have trouble with image ratio (especially with long width), try to use `--imgW 256`. 

Best

**Comment by mharsh1903** [comment]
We cannot give any random value of --imgh and --imgw  as it will give error,so i want to ask is there any way of assigning the value of width and height (For example: height and width must be multiple of 32 or some number or something else)

**Comment by kishcs** [comment]
What is recommended to do when the input images' size are dynamic in nature? Whether 32x100 resizing will create any prediction accuracy issue?

In my case, images are of various sizes as below: (logs printed for AlignCollate)
```
inside __call__: (87, 18)
inside __call__:[after resize] (100, 32)
inside __call__: (80, 18)
inside __call__:[after resize] (100, 32)
inside __call__: (94, 18)
inside __call__:[after resize] (100, 32)
inside __call__: (32, 23)
inside __call__:[after resize] (100, 32)
* * * 
inside __call__: (27, 20)
inside __call__:[after resize] (100, 32)
inside __call__: (27, 19)
inside __call__:[after resize] (100, 32)
inside __call__: (26, 18)
inside __call__:[after resize] (100, 32)
inside __call__: (30, 21)
inside __call__:[after resize] (100, 32)
inside __call__: (67, 24)
inside __call__:[after resize] (100, 32)
inside __call__: (30, 17)
inside __call__:[after resize] (100, 32)
inside __call__: (64, 20)
inside __call__:[after resize] (100, 32)
inside __call__: (28, 20)
inside __call__:[after resize] (100, 32)
```
