### ISSUE TITLE
when i running train.py,have an error ValueError: num_samples should be a positive integer value, but got num_samples=0

### ISSUE THREAD

**Issue by xiniang** [clovaai/deep-text-recognition-benchmark#52]
dataset_root: ./result
opt.select_data: ['/']
opt.batch_ratio: ['1.0']
--------------------------------------------------------------------------------
dataset_root:    ./result	 dataset: /
sub-directory:	/.	 num samples: 0
num total samples of /: 0 x 1.0 (total_data_usage_ratio) = 0
num samples of / per batch: 192 x 1.0 (batch_ratio) = 192
Traceback (most recent call last):
  File "train.py", line 279, in <module>
    train(opt)
  File "train.py", line 25, in train
    train_dataset = Batch_Balanced_Dataset(opt)
  File "/home/user/桌面/deep-text-recognition-benchmark-master/dataset.py", line 59, in __init__
    collate_fn=_AlignCollate, pin_memory=True)
  File "/home/user/anaconda3/envs/py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 176, in __init__
    sampler = RandomSampler(dataset)
  File "/home/user/anaconda3/envs/py36/lib/python3.6/site-packages/torch/utils/data/sampler.py", line 66, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0

**Comment by xiniang** [comment]
i had resloved ,thank you

**Comment by xiniang** [comment]
Thank you



------------------ 原始邮件 ------------------
发件人: "Baek JeongHun"<notifications@github.com>; 
发送时间: 2019年8月10日(星期六) 中午1:13
收件人: "clovaai/deep-text-recognition-benchmark"<deep-text-recognition-benchmark@noreply.github.com>; 
抄送: "　"<597406404@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [clovaai/deep-text-recognition-benchmark] when i runningtrain.py,have an error ValueError: num_samples should be a positive integervalue, but got num_samples=0 (#52)




Closed #52.

**Comment by xiniang** [comment]
I have one question, if I  used one image the num_samples = 1?If I used two images the num_samples = 2? 




------------------ 原始邮件 ------------------
发件人: "Baek JeongHun"<notifications@github.com>;
发送时间: 2019年8月10日(星期六) 中午1:13
收件人: "clovaai/deep-text-recognition-benchmark"<deep-text-recognition-benchmark@noreply.github.com>;
抄送: "　"<597406404@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [clovaai/deep-text-recognition-benchmark] when i runningtrain.py,have an error ValueError: num_samples should be a positive integervalue, but got num_samples=0 (#52)




Closed #52.

**Comment by ku21fan** [comment]
@xiniang Yes, but notice that `num_samples` is the number of samples after filtering.
filtering is performed here https://github.com/clovaai/deep-text-recognition-benchmark/blob/master/dataset.py#L130-L148

**Comment by youngsirsk** [comment]
I have same problem, could you tell me how to resolve it? Thanks!
