### ISSUE TITLE
how to output the probability of atten?

### ISSUE THREAD

**Issue by Juandai8401** [clovaai/deep-text-recognition-benchmark#58]
i want to output the confidence of cnn+rnn+atten, Do you have any good suggestions?

**Comment by ku21fan** [comment]
Hello, 

If you want to calculate the output probability of Atten (by greedy decoding)
1. softmax this line, https://github.com/clovaai/deep-text-recognition-benchmark/blob/master/modules/prediction.py#L53 
It will guarantee to change probs_step into the probability distribution, whose values are in 0~1, at that step.

2. Then get the max value of softmax(probs_step)
This will be the probability of predicted 'character' at that step.

3. Then multiply these values in every step.
This will be the probability of predicted 'word'.
(maybe you need to exclude pad token)

Best

**Comment by nbhupendra** [comment]
> i want to output the confidence of cnn+rnn+atten, Do you have any good suggestions?

@Juandai8401  have you solved this? i also looking for the same. Can you please also help me get probability. Really appreciate.

**Comment by Juandai8401** [comment]
If you want to calculate the output probability of Atten (by greedy decoding)

    softmax this line, https://github.com/clovaai/deep-text-recognition-benchmark/blob/master/modules/prediction.py#L53
    It will guarantee to change probs_step into the probability distribution, whose values are in 0~1, at that step.

    Then get the max value of softmax(probs_step)
    This will be the probability of predicted 'character' at that step.

    Then multiply these values in every step.
    This will be the probability of predicted 'word'.
    (maybe you need to exclude pad token)


it is useful!!

**Comment by Juandai8401** [comment]
> 
> 
> > i want to output the confidence of cnn+rnn+atten, Do you have any good suggestions?
> 
> @Juandai8401 have you solved this? i also looking for the same. Can you please also help me get probability. Really appreciate.

If you want to calculate the output probability of Atten (by greedy decoding)

    softmax this line, https://github.com/clovaai/deep-text-recognition-benchmark/blob/master/modules/prediction.py#L53
    It will guarantee to change probs_step into the probability distribution, whose values are in 0~1, at that step.

    Then get the max value of softmax(probs_step)
    This will be the probability of predicted 'character' at that step.

    Then multiply these values in every step.
    This will be the probability of predicted 'word'.
    (maybe you need to exclude pad token)
  it is useful!!

**Comment by nbhupendra** [comment]
> > > i want to output the confidence of cnn+rnn+atten, Do you have any good suggestions?
> > 
> > 
> > @Juandai8401 have you solved this? i also looking for the same. Can you please also help me get probability. Really appreciate.
> 
> If you want to calculate the output probability of Atten (by greedy decoding)
> 
> ```
> softmax this line, https://github.com/clovaai/deep-text-recognition-benchmark/blob/master/modules/prediction.py#L53
> It will guarantee to change probs_step into the probability distribution, whose values are in 0~1, at that step.
> 
> Then get the max value of softmax(probs_step)
> This will be the probability of predicted 'character' at that step.
> 
> Then multiply these values in every step.
> This will be the probability of predicted 'word'.
> (maybe you need to exclude pad token)
> ```
> 
> it is useful!!

I got the predictive character max value but no idea how to multiple them. Can you please help me for this.
