### ISSUE TITLE
cannot download data

### ISSUE THREAD

**Issue by CuriousCat-7** [clovaai/deep-text-recognition-benchmark#59]
Hello authors,

Thank you for sharing your code, data and pre-trained model here. 
But the data listed in README.md has been downloaded too many times, and it has been forbidden to download any more. To make people replica your work, could you find some other ways to share the data again?

Thanks !

**Comment by ku21fan** [comment]
Hello,

Datasets in the Google drive can still download now.
Is this issue on the Baidu net disk?
Baidu net disk is for the Chinese users, and we don't have used Baidu disk a lot. 
So we could not predict that there is a limit.

We will try to find some other ways, but it is difficult for us to find proper ways.
Do you have some ideas about other ways for Chinese users?
Is dropbox accessible in China?

Best

**Comment by CuriousCat-7** [comment]
> Hello,
> 
> We can still download datasets in the Google drive now.
> Is this issue on the Baidu net disk?
> Baidu net disk is for the Chinese users, and we don't have used Baidu disk a lot.
> So we could not predict that there is a limit.
> 
> We will try to find some other ways, but it is difficult for us to find proper ways.
> Do you have some ideas about other ways for Chinese users?
> Is dropbox accessible in China?
> 
> Best

Really? I cannot download from google drive. But that reminds me that I should use Baidu disk in Chinese Mainland. Thank you.
