### ISSUE TITLE
new question

### ISSUE THREAD

**Issue by CXY573** [clovaai/deep-text-recognition-benchmark#6]
I don't know if you can provide the code to process the mat file in http://www.robots.ox.ac.uk/~vgg/data/scenetext/. 
There is no documentation in it. I don't know how to deal with this file.

It is so wired.
The 'wordBB' of  8/ballet_106_0.jpg has 15 points, as we know 8 points is enough to describ a box,but why it provide 15 points

**Comment by ku21fan** [comment]
Yes, some examples of SynthText dataset are weird, so we conducted some validation checks for each bounding box.
We hope that this code will help you. 
[crop_by_word_bb.zip](https://github.com/clovaai/deep-text-recognition-benchmark/files/3125995/crop_by_word_bb.zip)

Best,

**Comment by alwc** [comment]
@ku21fan Where do we find the `gt.mat` file?

**Comment by ku21fan** [comment]
@alwc 
Hi, download the `SynthText.zip` file from here http://www.robots.ox.ac.uk/~vgg/data/scenetext/ 
`gt.mat` file is in the `SynthText.zip` file.

**Comment by ZDDEAN** [comment]
请问如何能分享一下synthtext格式转换为icdar格式的脚本吗，谢谢鸭
