### ISSUE TITLE
what is the difference between data_lmdb_baidu.xx and data_lmdb_reuploaded.xx?

### ISSUE THREAD

**Issue by eepaul** [clovaai/deep-text-recognition-benchmark#62]
Thanks for your great work.
I am downloading your dataset from baidu and I noticed there are 2 zips (data_lmdb_baidu and data_lmdb_reuploaded? what is the difference?

**Comment by ku21fan** [comment]
Hello, 

They are the same file, but sometimes data_lmdb_baidu.zip could not be unzipped for some reason. 
So I literally reuploaded data_lmdb_reuploaded, and it works.

Thus, I recommend using data_lmdb_reuploaded.zip
I just renamed the folder.
Sorry for confusing you. 

Best

**Comment by eepaul** [comment]
Thanks for your quick reply.
Another question for the SynthText dataset:  did you crop the word out of the original dataset(http://www.robots.ox.ac.uk/~vgg/data/scenetext/) by the quadrilateral bounding box and then rotate the cropped patch horizontal?
