### ISSUE TITLE
path does not exist error while creating custom dataset

### ISSUE THREAD

**Issue by omersert** [clovaai/deep-text-recognition-benchmark#65]
Hi I wanted to create my own dataset I used these instructions [https://github.com/clovaai/deep-text-recognition-benchmark#when-you-need-to-create-lmdb-dataset](url) 
When I issue the command 
python3 create_lmdb_dataset.py --inputPath data/ --gtFile data/gt.txt --outputPath result/
I get the eror 
![image](https://user-images.githubusercontent.com/53513065/64341446-09344800-cff1-11e9-8383-795c52458564.png)

it says the path does not exist but it actually exists.
What can I do to prevent this error?

**Comment by inouetaka** [comment]
@omersert 
Does the path written in gtFile match the actual path?

**Comment by omersert** [comment]
Yes they're identical.

**Comment by ku21fan** [comment]
Hello, 

I guess something would be wrong..
I doubted the actual path as @inouetaka said.

I wonder the output of `os.path.exists(imagePath)`.
Can you add and print the result of `print(os.path.exists(imagePath))` as below?
```
        print(os.path.exists(imagePath)) <-- add this at Line 53 in create_lmdb_dataset.py
        if not os.path.exists(imagePath):
            print('%s does not exist' % imagePath)
            continue
```

**Comment by omersert** [comment]
@ku21fan Hi,
I did what you said and here is what I got as an output
![image](https://user-images.githubusercontent.com/53513065/64412990-58ce4e80-d099-11e9-8bfa-0ba533ca5cf2.png)
and this is a screenshot from my gt.txt file
![image](https://user-images.githubusercontent.com/53513065/64413096-8e733780-d099-11e9-8953-dc11c6005913.png)

**Comment by ku21fan** [comment]
@omersert 
I found the cause and solution! 
![스크린샷_090619_054429_PM](https://user-images.githubusercontent.com/7953971/64414232-fba0c000-d0cd-11e9-854b-9f9b09ca1ac0.jpg)
If the second argument started with `/home/` (specifically `/`), the first argument (= inputPath =data/ ) was ignored.
It was unexpectable for me, I didn't know this weird behavior of `os.path.join` function.
Sorry about that.

So, can you make and try with new_gt.txt file? 
which removed `/home/~~~~~-benchamrk/data/` in each line. 
i.e. `/home/~~~~~-benchamrk/data/resimler/res_30001_0000166--.jpg` to `resimler/res_30001_0000166--.jpg`

Best

**Comment by omersert** [comment]
@ku21fan Now it works fine.
Thank you so much.
