### ISSUE TITLE
image size

### ISSUE THREAD

**Issue by mharsh1903** [clovaai/deep-text-recognition-benchmark#70]
We cannot give any random value of --imgh and --imgw as it will give error,so i want to ask is there any way of assigning the value of width and height (For example: height and width must be multiple of 32 or some number or something else)

**Comment by 13438960761** [comment]
@mharsh1903 you can change  width and height. i changed.

**Comment by ku21fan** [comment]
Hello, 

As @13438960761 said, you can change width and height, (we use adaptive average pooling [here](https://github.com/clovaai/deep-text-recognition-benchmark/blob/master/model.py#L50))
However, probably there are some constraints depending on the module, such as imgH >= 32 and imgW >= 8.

Best.

**Comment by anavc94** [comment]
> Hello,
> 
> As @13438960761 said, you can change width and height, (we use adaptive average pooling [here](https://github.com/clovaai/deep-text-recognition-benchmark/blob/master/model.py#L50))
> However, probably there are some constraints depending on the module, such as imgH >= 32 and imgW >= 8.
> 
> Best.

Hi, @ku21fan 

I am sorry for your inconvenience but I have not understand very well what I have to change in the code to be able to set a imgH and imgW, could you please explain? Thank you in advance
