### ISSUE TITLE
How to detect special characters?

### ISSUE THREAD

**Issue by kalai2033** [clovaai/deep-text-recognition-benchmark#72]
Hi ,
   Thanks for such a nice recognition model. I have used the pre trained model "TPS-ResNet-BiLSTM-Attn.pth" for text recognition. I need help with detecting special characters. For instance, in a word "www.ab-c@css.com" the special characters like '.' , '@', '-' are not detected in the output. i tried both Attn and CTC as prediction modes. Also i tried changing the argument character, i was getting below error

RuntimeError: Error(s) in loading state_dict for DataParallel:
	size mismatch for module.Prediction.attention_cell.rnn.weight_ih: copying a param with shape torch.Size([1024, 294]) from checkpoint, the shape in current model is torch.Size([1024, 307]).

**Comment by ku21fan** [comment]
Hello, 

TPS-ResNet-BiLSTM-Attn.pth is not trained with special characters.
Try to download and use [TPS-ResNet-BiLSTM-Attn-case-sensitive.pth](https://drive.google.com/open?id=1ajONZOgiG9pEYsQ-eBmgkVbMDuHgPCaY) 
This model is trained with special characters.

Best
