### ISSUE TITLE
not able to change model parameters

### ISSUE THREAD

**Issue by mharsh1903** [clovaai/deep-text-recognition-benchmark#73]
I think we cannot change model parameters like character set, image width ,height,if we take sensitive or case sensitive pretrained weights .If not ,then only option is train from scratch if we want different character set or other parameters like width and height

**Comment by ku21fan** [comment]
Hello, 

I recommend 
1. Load with `model.load_state_dict(torch.load(opt.saved_model), strict=False)` 
instead of `model.load_state_dict(torch.load(opt.saved_model))`
2. Then fine-tuning with your additional network or parameters.

Hope it helps.
Best.

**Comment by mharsh1903** [comment]
Thanks for your reply,but even after Load with model.load_state_dict(torch.load(opt.saved_model), strict=False), Iam still getting this error(find below) when change input size.

RuntimeError: Error(s) in loading state_dict for DataParallel:
        size mismatch for module.Transformation.GridGenerator.P_hat: copying a param with shape torch.Size([3200, 23]) from checkpoint, the shape in current model is torch.Size([15000, 23]).

**Comment by mostafahadian** [comment]
@mharsh1903 it might be because of your --character argument. Check: there should not be any difference between your train.py's character argument and demp.py's character argument.
```
parser.add_argument('--character', type=str, default='abc...'
```

**Comment by kingwpf** [comment]
I think this error caused by different image width between training and eval.
