### ISSUE TITLE
how to handle corrupt imgs in lmdb dataset 

### ISSUE THREAD

**Issue by crazysal** [clovaai/deep-text-recognition-benchmark#74]
Hi, 

In the dataset provided (the lmdb files on google drive)
I came across some instances of files being corrupt images for example : 
in training/MJ/MJ_test : 
image_key  = 'image-000001425'
in training/MJ/MJ_valid : 
image_key  = 'image-000016379'
on visualizing the following is rendered (in both cases) :
![Figure_1](https://user-images.githubusercontent.com/6873582/65442138-a7018280-ddf9-11e9-9069-033c14351e30.png)

How to detect such cases ?

**Comment by ku21fan** [comment]
Hello, 

Currently, we did not handle these cases in MJSynth dataset.
I guess that such cases occurs when the weird font was used.

One remedy would be 
1. If the output images of such cases are the same, save the output images  (the image you attached).
2. then filter images `if images == saved images in 1.`.

Best
