### ISSUE TITLE
.pth file how to used

### ISSUE THREAD

**Issue by xiniang** [clovaai/deep-text-recognition-benchmark#75]
Hi,I used myself data prodeced a best_accuracy.pth file in saved_models files,but i don't konw how to used it for detection.

**Comment by inouetaka** [comment]
CUDA_VISIBLE_DEVICES=0 python3 test.py \
--eval_data data_lmdb_release/evaluation --benchmark_all_eval \
--Transformation None --FeatureExtraction VGG --SequenceModeling BiLSTM --Prediction CTC \
--saved_model saved_models/None-VGG-BiLSTM-CTC-Seed1111/best_accuracy.pth

**Comment by xiniang** [comment]
Thanks very much for my heart.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "inouetaka"<notifications@github.com&gt;; 
发送时间: 2019年9月25日(星期三) 上午8:58
收件人: "clovaai/deep-text-recognition-b"<deep-text-recognition-benchmark@noreply.github.com&gt;; 
抄送: "　"<597406404@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [clovaai/deep-text-recognition-benchmark] .pth file how to used (#75)




CUDA_VISIBLE_DEVICES=0 python3 test.py 
 --eval_data data_lmdb_release/evaluation --benchmark_all_eval 
 --Transformation None --FeatureExtraction VGG --SequenceModeling BiLSTM --Prediction CTC 
 --saved_model saved_models/None-VGG-BiLSTM-CTC-Seed1111/best_accuracy.pth
