### ISSUE TITLE
--rgb

### ISSUE THREAD

**Issue by xiniang** [clovaai/deep-text-recognition-benchmark#77]
Hi,it will have an error when I add --rgb parameter on training time.
Ex:
RuntimeError: The expanded size of the tensor (1) must match the existing size (3) at non-singleton dimension 0.  Target sizes: [1, 32, 100].  Tensor sizes: [3, 32, 100]

**Comment by ku21fan** [comment]
Hello, 

Did you use pretrained model? 
or load default model (which is not use `--rgb`) then train with `--rgb` option?
If you start to training with `--rgb` option it would work. such as
```
CUDA_VISIBLE_DEVICES=0 python3 train.py \
--train_data data_lmdb_release/training --valid_data data_lmdb_release/validation \
--select_data MJ-ST --batch_ratio 0.5-0.5 \
--Transformation None --FeatureExtraction VGG --SequenceModeling BiLSTM --Prediction CTC --rgb
```

Best
