### ISSUE TITLE
how to get accuracy score of each word

### ISSUE THREAD

**Issue by nbhupendra** [clovaai/deep-text-recognition-benchmark#78]
how to get accuracy score of each word. Please help. really appreciate.

**Comment by nbhupendra** [comment]
@ku21fan Please help.

**Comment by inouetaka** [comment]
```
from nltk.metrics.distance import edit_distance

distance = edit_distance(pred, gt) / max([len(pred), len(gt)])
```

**Comment by nbhupendra** [comment]
> ```
> from nltk.metrics.distance import edit_distance
> 
> distance = edit_distance(pred, gt) / max([len(pred), len(gt)])
> ```

where i have to add these lines? Can you plz guide me.

**Comment by nbhupendra** [comment]
where i have to add these lines in demo.py? Can you plz guide me. i want confidence score of predicted word in demo.py.

**Comment by ku21fan** [comment]
Hello, 

1. load your gt list of each word images
2. change this snippet 
https://github.com/clovaai/deep-text-recognition-benchmark/blob/235095fc9a80e0987582958aabe376b588d0c419/demo.py#L72-L76
into below to count correct case and calculate edit distance
```
 for img_name, pred, gt in zip(image_path_list, preds_str, gt_list): 
     if 'Attn' in opt.Prediction: 
         pred = pred[:pred.find('[s]')]  # prune after "end of sentence" token ([s]) 
     if pred == gt:
        n_correct += 1
     distance = edit_distance(pred, gt) / max([len(pred), len(gt)])
     print(f'image name:{img_name}\t pred:{pred}\t gt:{gt}\t{str(pred == gt)}\t edit distance:{distance}') 
```

Best

**Comment by nbhupendra** [comment]
> Hello,
> 
> 1. load your gt list of each word images
> 2. change this snippet
>    https://github.com/clovaai/deep-text-recognition-benchmark/blob/235095fc9a80e0987582958aabe376b588d0c419/demo.py#L72-L76
>    
>    into below to count correct case and calculate edit distance
> 
> ```
>  for img_name, pred, gt in zip(image_path_list, preds_str, gt_list): 
>      if 'Attn' in opt.Prediction: 
>          pred = pred[:pred.find('[s]')]  # prune after "end of sentence" token ([s]) 
>      if pred == gt:
>         n_correct += 1
>      distance = edit_distance(pred, gt) / max([len(pred), len(gt)])
>      print(f'image name:{img_name}\t pred:{pred}\t gt:{gt}\t{str(pred == gt)}\t edit distance:{distance}') 
> ```
> 
> Best

Hi,

I guess there is misunderstanding in question. I dont want to calculate distance with gt. i want the confidence score for read word by Attn. Like suppose if i word read by attn is "hello" and is confidence is 99% or something so that i could discard non english or junk character or word.

Please help @ku21fan @inouetaka
