### ISSUE TITLE
Could you kindly provide the premade lmdb 'data_lmdb_release.zip' md5 code?

### ISSUE THREAD

**Issue by sonack** [clovaai/deep-text-recognition-benchmark#87]
It is a little bit too big for me.... and I wonder if I get the same file with you. So could you please provide the md5sum of the 19Gb data_lmdb_release.zip file? Thanks for your contribution!

**Comment by ku21fan** [comment]
Hello,

md5sum of the 19Gb data_lmdb_release.zip file is
1441dc23fb261a252470cc978cefba3f

Best

**Comment by sonack** [comment]
thank you very much，hope it appended in the readme



发自我的iPhone


------------------ Original ------------------
