### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by SealQ** [clovaai/deep-text-recognition-benchmark#89]
How long do you need to train your data? Why do I need a long time to train with my own data? It still takes me about a week to train the model once with three 1080ti GPUs.

**Comment by ku21fan** [comment]
Hello, 

With our training dataset which we released, we took about 2.5~3 days with TPS-ResNet-BiLSTM-Attn.
and took about 10 Hours with CRNN (None-VGG-BiLSTM-CTC).
(with imgH 32, imgW 100, num_iter 300K, batch size 192, batch_max_length 25)

In our code, when we use multi-GPU, we multiply the batch size with the number of GPUs (by default setting).
I recommend adjusting batch_size (or change this line.)
https://github.com/clovaai/deep-text-recognition-benchmark/blob/4381a5fb46f328984dad1d2fe255728eab328f17/train.py#L284

Best
