### ISSUE TITLE
Image's width should be fixed?

### ISSUE THREAD

**Issue by 1033020837** [clovaai/deep-text-recognition-benchmark#9]
Does train images' width should be fixed?

**Comment by kdrl** [comment]
No, it can be different.
But a batch of images will be resized to `(imgH, imgW)` as a preprocessing, before it is passed to the model.

https://github.com/clovaai/deep-text-recognition-benchmark/blob/f1ab5146b70cac5eb3b2134c6f50bc4812e50357/dataset.py#L188

https://github.com/clovaai/deep-text-recognition-benchmark/blob/f1ab5146b70cac5eb3b2134c6f50bc4812e50357/dataset.py#L57

**Comment by kdrl** [comment]
No, it can be different.
But the images will be resized to `(imgH, imgW)` as a preprocessing of input batch, before it is passed to the model.

https://github.com/clovaai/deep-text-recognition-benchmark/blob/f1ab5146b70cac5eb3b2134c6f50bc4812e50357/dataset.py#L188

https://github.com/clovaai/deep-text-recognition-benchmark/blob/f1ab5146b70cac5eb3b2134c6f50bc4812e50357/dataset.py#L57

**Comment by ku21fan** [comment]
As GEEWOOK said, the image size resized to fixed size by default.
But you can test PAD option which keeps the image width/height ratio.
(I just added PAD option to this repo now, you can use with '--PAD')
​
