### ISSUE TITLE
Use --Trans TPS --Pad and set ImgW = 640

### ISSUE THREAD

**Issue by liangzimei** [clovaai/deep-text-recognition-benchmark#92]
in my train set, most of samples' width are smaller than 640 , when Use --Trans TPS --Pad and set ImgW = 640, that means most samples would pad 0 in the right.  
In this config, acc would be worse than '--Trans TPS pad = False imgW=100'. do you have any experience on this config.

**Comment by ku21fan** [comment]
Hello, 

I have not tested `--imgW 640`. 
For wide image, I have tested `--imgW 256` or `384` and it works fine.

I guess that 640 is too wide to recognize images with short labeled such as 'a' or 'an'.

Best

**Comment by liangzimei** [comment]
in config of '--pad and imgW=640', it keep the ratio of text, so it does not affect short labeled text. The acc is normal now. But in these experiments, i found the character in  wide text gets smaller from left to right after TPS. ~~Is it caused by fc2 bias' initialization in Location Net?~~  It didnt improve when trying different  bias initializations. 
Thanks in advance.
