### ISSUE TITLE
How to set the proper parameter under the different  scene?

### ISSUE THREAD

**Issue by 13438960761** [clovaai/deep-text-recognition-benchmark#93]
How to set the proper parameter under the different  scene? for example , i want to recogize the name , how to make up the parameters for None\TPS, VGG|RCNN|ResNet,None|BiLSTM, CTC|Attn?
 I can't understand deeply when should i use CTC or Atten?
 Would you please give me some advice? thank you very much.

**Comment by boy977** [comment]
1. Read their paper
2. Figure out what TPS/VGG/BiLSTM/CTC/Attn mean (by Googling)
3. Try some combinations yourself. Try and try until you find your best combination
P/s: They said their best combination of accuracy is TPS + ResNet + BiLSTM + Attn

**Comment by ku21fan** [comment]
Hello, 

1. when should i use CTC or Atten?
-> In our paper, we suggest CTC for fast inference time and Attn for better accuracy.

2. Recommend to use TPS + ResNet + BiLSTM + Attn for better accuracy, if you don't care about memory/inference time.

3. If you only need to recognize name dataset, modifying the `--imgW` and `--batch_max_length` would be helpful.

@boy977 Thank you for answering :D

Best
