### ISSUE TITLE
 changing model parameters with pretrained weights

### ISSUE THREAD

**Issue by mharsh1903** [clovaai/deep-text-recognition-benchmark#96]
Thanks for your reply,but even after Load with model.load_state_dict(torch.load(opt.saved_model), strict=False), Iam still getting this error(find below) when change input size.

RuntimeError: Error(s) in loading state_dict for DataParallel:
size mismatch for module.Transformation.GridGenerator.P_hat: copying a param with shape torch.Size([3200, 23]) from checkpoint, the shape in current model is torch.Size([15000, 23]).

Please reply asap

**Comment by ku21fan** [comment]
Hello, 

comment out these lines
https://github.com/clovaai/deep-text-recognition-benchmark/blob/9a6f6678b1ec3343fc6891ff964ac9af1b1d04c7/modules/transformation.py#L93-L95
and un-comment out these lines (use these lines)
https://github.com/clovaai/deep-text-recognition-benchmark/blob/9a6f6678b1ec3343fc6891ff964ac9af1b1d04c7/modules/transformation.py#L96-L98
Then fine-tuning
Hope it helps. :)

Best

**Comment by itmorn** [comment]
hello，@ku21fan
When I add new characters to the "characters " and fine tune the model，I got the following mistakes. Could you give me some help?
parser.add_argument('--character', type=str, default='0123456789abcdefghijklmnopqrstuvwxyz在任何场合，说服任何人', help='character label')

`ssh://zyc@10.100.17.47:22/home/zyc/pyvenv/basic_DL/bin/python3 -u /home/zyc/workplace/deep-text-recognition-benchmark/train.py --train_data data_lmdb_release/training --valid_data data_lmdb_release/validation --Transformation TPS --FeatureExtraction ResNet --SequenceModeling BiLSTM --Prediction Attn --PAD --FT --saved_model TPS-ResNet-BiLSTM-Attn.pth
------ Use multi-GPU setting ------
if you stuck too long time with multi-GPU setting, try to set --workers 0
Filtering the images containing characters which are not in opt.character
Filtering the images whose label is longer than opt.batch_max_length
--------------------------------------------------------------------------------
dataset_root: data_lmdb_release/training
opt.select_data: ['/']
opt.batch_ratio: ['1']
--------------------------------------------------------------------------------
dataset_root:    data_lmdb_release/training	 dataset: /
sub-directory:	/.	 num samples: 4
num total samples of /: 4 x 1.0 (total_data_usage_ratio) = 4
num samples of / per batch: 384 x 1.0 (batch_ratio) = 384
--------------------------------------------------------------------------------
Total_batch_size: 384 = 384
--------------------------------------------------------------------------------
dataset_root:    data_lmdb_release/validation	 dataset: /
sub-directory:	/.	 num samples: 4
--------------------------------------------------------------------------------
model input parameters 32 256 20 1 512 256 49 64 TPS ResNet BiLSTM Attn
Skip Transformation.LocalizationNetwork.localization_fc2.weight as it is already initialized
Skip Transformation.LocalizationNetwork.localization_fc2.bias as it is already initialized
loading pretrained model from TPS-ResNet-BiLSTM-Attn.pth
Traceback (most recent call last):
  File "/home/zyc/workplace/deep-text-recognition-benchmark/train.py", line 315, in <module>
    train(opt)
  File "/home/zyc/workplace/deep-text-recognition-benchmark/train.py", line 82, in train
    model.load_state_dict(torch.load(opt.saved_model), strict=False)
  File "/home/zyc/pyvenv/basic_DL/lib/python3.6/site-packages/torch/nn/modules/module.py", line 769, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DataParallel:
	size mismatch for module.Prediction.attention_cell.rnn.weight_ih: copying a param with shape torch.Size([1024, 294]) from checkpoint, the shape in current model is torch.Size([1024, 305]).
	size mismatch for module.Prediction.generator.weight: copying a param with shape torch.Size([38, 256]) from checkpoint, the shape in current model is torch.Size([49, 256]).
	size mismatch for module.Prediction.generator.bias: copying a param with shape torch.Size([38]) from checkpoint, the shape in current model is torch.Size([49]).

Process finished with exit code 1
`

**Comment by AbdelsalamHaa** [comment]
Hello @ku21fan 
I did what you recommended witch is to comments some line in deep-text-recognition-benchmark/modules/transformation.py and uncomment some other but than I faced this issue. 

RuntimeError: Error(s) in loading state_dict for DataParallel:
	Unexpected key(s) in state_dict: "module.Transformation.GridGenerator.inv_delta_C", "module.Transformation.GridGenerator.P_hat".

**Comment by nag1045** [comment]
> Thanks for your reply,but even after Load with model.load_state_dict(torch.load(opt.saved_model), strict=False), Iam still getting this error(find below) when change input size.
> 
> RuntimeError: Error(s) in loading state_dict for DataParallel: size mismatch for module.Transformation.GridGenerator.P_hat: copying a param with shape torch.Size([3200, 23]) from checkpoint, the shape in current model is torch.Size([15000, 23]).
> 
> Please reply asap

did you solve this problem?
