### ISSUE TITLE
Add SPACE to target character sets

### ISSUE THREAD

**Issue by thaihaquang** [clovaai/deep-text-recognition-benchmark#97]
Dear authors. Thank you for your great project. I am trying training None-ResNet-BiLSTM-CTC model with my own training data. However, I founded that the performance is not good when there is any space between characters. Then I think I should add the SPACE to the character sets (current is "01234...abc...ABC.../\:!~"). Do you have any suggestions for this problem? If I want to add SPACE to char sets then how can I do, just " 0123.." or any special way?
Below is a nice result from your online demo. Do you add SPACE to charsets?
![image](https://user-images.githubusercontent.com/42860711/67452901-eb797b80-f64e-11e9-879a-f78292c9e8b3.png)

Thanks for your attention. I’m looking forward to your reply.

**Comment by ku21fan** [comment]
Hello, 

Just add space to char as you thought :)
It would work.
We added SPACE to charsets for web demo model.
And make sure your own training data contain SPACE also.

Best

**Comment by josmecedo** [comment]
Hey!
I'm facing the same problem and I don't have a lot of data neither computational power, I would like to know if you train your model with spaces and other characters such as '€', '£' and if you can share it!
Thank you in advance!
